'use strict';
/* =====================================================================
   三種世界觀（試玩版：第一章）
   劇情文字目前為暫定版本，系統與介面確定後再補完整劇情。
   {name} 玩家名字　{weapon} 目前武器名稱
   ===================================================================== */
const WORLDS = {
  /* ------------------------------------------------------------------ */
  school: {
    id: 'school', name: '國中生涯', icon: '🏫', theme: 'school', style: 'school', money: '積分',
    tagline: '在青嵐國中拿起文具，迎戰把課本弄亂的錯字妖！',
    focus: '第一章：字音字形',
    chapterName: '第一章．錯字大作戰',
    mapNames: { town1: '青嵐國中．前庭', route1: '後山步道', town2: '藝文中庭' },
    music: { town: 'town_school', route: 'route' },
    surnames: '陳林黃張李王吳劉蔡楊許鄭謝郭洪'.split(''),
    given: ['宇翔', '品妍', '子晴', '柏睿', '語彤', '承恩', '詠晴', '冠宇', '芷若', '家豪', '思妤', '亦辰', '沛涵', '宥廷', '欣妤', '睿哲'],
    titleLabel: '班級社團',
    genTitle() { return `${pick(['七', '八', '九'])}年${pick(['一', '二', '三', '五', '六', '八'])}班．${pick(['文學社', '圖書股長', '國文小老師', '朗讀社', '書法社', '辯論社'])}`; },
    weapons: {
      brush: ['自動鉛筆', '筆芯削得尖尖的，專門修正錯字與錯音。'], tome: ['成語字典', '厚厚一本，翻到哪一頁都是典故。'],
      scroll: ['國文課本', '翻開就能召喚古文與詩詞的力量。'], fan: ['彩色螢光筆', '畫重點專用，擅長看穿修辭。'],
      seal: ['放大鏡', '看清每個細節，擅長常識與閱讀。'], legend: ['金牌鋼筆', '傳說中會考滿分學長留下的鋼筆。'] },
    items: { heal: '運動飲料', heal2: '營養便當', wenqi: '提神巧克力', hint: '錦囊小抄' },
    prologue: [
      '這裡是青嵐國中。傳說每個文字裡都住著精靈，人們叫它們「詞靈」。',
      '最近，詞靈被錯字的力量汙染，變成了到處搗亂的「錯字妖」，把課本上的字詞弄得亂七八糟！',
      '{name}，拿起你的文具，把錯字妖一一打倒吧！',
      '先去前庭找國文老師——王老師。'],
    roles: {
      mentor: { kind: 'mentor', name: '王老師', look: { hair: '#2a2a30', cloth: '#5a7ab0', pants: '#3a3a48', glasses: 1 },
        intro: '早安，{name}！錯字妖越來越多了，你願意幫忙嗎？\n\n這三件文具都藏著國文的力量，挑一件當你的武器吧！',
        later: '累了嗎？讓老師幫你恢復一下精神……好了，加油！' },
      tip1: { name: '同學 阿哲', look: { hair: '#402818', cloth: '#f8f8f8', cloth2: '#3a58a0', style: 'school' },
        lines: ['「再接再厲」的「厲」通「礪」，是「磨利」的意思喔！'] },
      tip2: { name: '學姊 小雯', look: { hair: '#201818', cloth: '#f8f8f8', cloth2: '#3a58a0', gender: 'f', style: 'school' },
        lines: ['步道上的錯字妖看得見喔！不想打的話，繞過去就好。', '按 START（Enter）打開選單，可以換武器、看錯題本。'] },
      tip6: { name: '工友伯伯', look: { hair: '#909090', cloth: '#6a8a6a', hat: '#4a6a4a' },
        lines: ['這棟是舊禮堂，還在整修中，下一章才會開放喔。'] },
      trainerA: { kind: 'trainer', name: '七年級 阿胖', look: { hair: '#3a2a20', cloth: '#f8f8f8', cloth2: '#3a58a0', style: 'school', bag: '#3a8a48' },
        foe: { lv: 4, hpMul: 1.3, weak: ['詞義'], moves: [['注音飛彈', ['字音'], 40], ['錯字連發', ['字形'], 40]] }, reward: 150,
        intro: '嘿！我們的眼神對上了，來一場國文對決吧！', win: '哇，你好厲害……我回去多背幾個注音！', after: '「躊躇」念作ㄔㄡˊ ㄔㄨˊ，我終於記住了。' },
      trainerB: { kind: 'trainer', name: '八年級 小芸', look: { hair: '#5a3020', cloth: '#f8f8f8', cloth2: '#3a58a0', gender: 'f', style: 'school', bag: '#8a58c8' },
        foe: { lv: 5, hpMul: 1.4, weak: ['字音'], moves: [['詞語陷阱', ['詞義'], 45], ['成語考驗', ['成語'], 45]] }, reward: 220,
        intro: '新生？學姊來考考你！', win: '不錯嘛，基本功很扎實！', after: '「差強人意」是「大致令人滿意」，不是「很差」喔！' },
      questGiver: { kind: 'quest', name: '巡山伯伯', look: { hair: '#909090', cloth: '#6a8a6a', hat: '#c8a860' },
        offer: '步道上的「錯字蟲」越來越多了……可以幫我消滅 3 隻嗎？', progress: '還差一點喔！錯字蟲通常躲在草叢裡。', done: '太感謝了！這些給你，路上小心。', after: '步道乾淨多了，謝謝你！' },
      rival: { kind: 'rival', name: '同班同學 程昊', look: { hair: '#1a1a24', cloth: '#f8f8f8', cloth2: '#c83838', style: 'school', bag: '#303038' },
        foe: { lv: 6, hpMul: 1.6, weak: ['成語'], moves: [['快問快答', ['字音', '字形'], 45], ['搶答', ['詞義'], 50]] }, reward: 300,
        intro: '喂，{name}！聽說你拿到了{weapon}？\n\n別以為這樣就能當英雄。來比比看，誰才是班上最強的！', win: '可惡……下次我一定會贏！', after: '我先去練功了，別太得意！' },
      gym1: { kind: 'gym', name: '風紀股長 林小晴', badge: '字形徽章', badgeColor: '#d07a1a', reward: 600, rewardWeapon: 'seal',
        look: { hair: '#181820', cloth: '#f8f8f8', cloth2: '#c83838', gender: 'f', style: 'school', bag: '#c83838' },
        foe: { lv: 8, hpMul: 2.2, weak: ['修辭'], cats: ['字音', '字形'], moves: [['紅筆訂正', ['字形'], 50], ['注音審判', ['字音'], 50], ['錯字全殲', ['字音', '字形'], 65]] },
        intro: '我是風紀股長林小晴！錯字、錯音，一個都別想逃過我的眼睛！\n\n本關考「字音」與「字形」，準備好了嗎？',
        win: '……你的字音字形功力，我服了。', after: '形近字要從部首判斷意思，例如「睫」有目字旁，所以是「迫在眉睫」。' },
      locked2: { name: '成語社社長 吳大明', look: { hair: '#2a2a2a', cloth: '#f8f8f8', cloth2: '#3a58a0', style: 'school', glasses: 1 },
        lines: ['我是成語社社長吳大明。等第二章開放，我們再來一決高下！（試玩版尚未開放）'] },
      trainerC: { kind: 'trainer', name: '九年級 學長阿傑', look: { hair: '#1a1a20', cloth: '#f8f8f8', cloth2: '#3a58a0', style: 'school', bag: '#303038' },
        foe: { lv: 7, hpMul: 1.4, weak: ['字形'], moves: [['會考題', ['閱讀'], 50], ['修辭攻勢', ['修辭'], 50]] }, reward: 400,
        intro: '會考倒數中！陪我練練手吧！', win: '你這實力，會考穩了！', after: '「時間就是金錢」用的是譬喻中的「暗喻」，喻詞是「是」。' },
      guard: { name: '糾察隊員', look: { hair: '#202020', cloth: '#f8f8f8', cloth2: '#d8b020', style: 'school', hat: '#d8b020' },
        lines: ['北邊是往第二章的路，目前還在施工中！'] },
      tip4: { name: '圖書館志工', look: { hair: '#6a3a2a', cloth: '#58a888', gender: 'f' },
        lines: ['風紀股長就在西邊那棟樓前。她只出「字音」和「字形」題，但聽說她不太擅長「修辭」……步道上的寶箱裡好像有螢光筆喔！'] },
      tip5: { name: '美術班同學', look: { hair: '#c86a3a', cloth: '#f8f8f8', cloth2: '#3a58a0', gender: 'f', style: 'school', bag: '#e86ab0' },
        lines: ['中庭西邊的草叢有比較強的錯字妖，可以去那裡練等級！'] },
    },
    doors: {
      home: { kind: 'home', text: '媽媽：「要出門啦？別忘了帶聯絡簿！」\n\n（在家休息了一下，氣血全滿了！）' },
      heal: { kind: 'heal', text: '保健室阿姨：「受傷了嗎？來，休息一下！」' },
      shop: { kind: 'shop', text: '福利社阿姨：「歡迎光臨！要買點什麼？」' },
      gymdoor: { kind: 'text', text: '門上貼著：「字音字形關　關主：風紀股長 林小晴」' },
      hall1: { kind: 'text', text: '舊禮堂的門上了鎖。（下一章開放）' },
      hall2: { kind: 'text', text: '門上貼著：「成語社」。（下一章開放）' },
    },
    signs: { sign_town1: '青嵐國中．前庭\n↑ 後山步道', sign_route1: '後山步道\n↑ 藝文中庭　↓ 前庭', sign_town2: '藝文中庭\n西：字音字形關' },
    gates: { needWeapon: '王老師：「等等！{name}，步道上有錯字妖，先來選一件武器吧！」', trialEnd: '糾察隊員：「前面是第二章的路，還在施工中！」（試玩版到此為止）' },
    ending: ['林小晴：「錯字妖的源頭，好像在學校更深的地方……」', '王老師：「{name}，第一章的挑戰，你完成了！」'],
  },

  /* ------------------------------------------------------------------ */
  literati: {
    id: 'literati', name: '文人墨客生涯', icon: '🖌️', theme: 'literati', style: 'literati', money: '文',
    tagline: '執筆為劍，在翰墨大陸向詩仙李白請益！',
    focus: '第一章：詩詞與常識',
    chapterName: '第一章．詩仙醉月',
    mapNames: { town1: '青蓮書院', route1: '曲水山徑', town2: '長安．東市' },
    music: { town: 'town_literati', route: 'route' },
    surnames: '李蘇王謝沈柳顧韓陸杜白范'.split(''),
    given: ['清', '雲', '翰', '墨', '青', '硯', '詠', '瑾', '書', '竹', '懷瑾', '子衿', '若水', '遠山', '聽雨', '采薇'],
    titleLabel: '字號',
    genTitle() { return `字${pick(['子', '伯', '仲', '季', '文', '德'])}${pick(['瞻', '安', '遠', '思', '明', '修', '然', '和'])}，號${pick(['青竹', '聽松', '臨江', '望月', '南山', '墨池', '聽雨', '清溪'])}${pick(['居士', '散人', '先生', '山人'])}`; },
    weapons: {
      brush: ['狼毫筆', '筆鋒剛勁，一點一畫都能辨正字形字音。'], tome: ['竹簡', '刻滿成語典故的古老竹簡。'],
      scroll: ['玉笛', '吹奏時會浮現古詩與古文。'], fan: ['宣紙扇', '扇面題滿詩句，擅長修辭。'],
      seal: ['端硯', '名硯之首，研出的墨能增長見聞。'], legend: ['松煙古墨', '傳說中文曲星留下的古墨。'] },
    items: { heal: '參茶', heal2: '靈芝', wenqi: '墨香', hint: '錦囊' },
    prologue: [
      '在古今文人齊聚的「翰墨大陸」，每一個字都有靈魂，人們稱之為「詞靈」。',
      '近來文曲星光黯淡，詞靈受到墨氣汙染，化為作亂的「字妖」，連詩人的佳句都被改得面目全非。',
      '{name}，你是青蓮書院新來的學子。執筆為劍，平定字妖之亂吧！',
      '先去拜見書院的周山長。'],
    roles: {
      mentor: { kind: 'mentor', name: '周山長', look: { hair: '#d8d8d8', cloth: '#6a5a8a', beard: 1, style: 'literati' },
        intro: '學子{name}，來得正好。「工欲善其事，必先利其器」。\n\n這三件文房之寶，選一件作你的兵器吧。',
        later: '來，老夫替你調息片刻……好了，去吧！' },
      tip1: { name: '書僮 小硯', look: { hair: '#2a2a2a', cloth: '#6a9ac8', style: 'literati', bun: 1 },
        lines: ['文房四寶是筆、墨、紙、硯。書院裡的兵器，都是從文房四寶變來的呢！'] },
      tip2: { name: '賣花姑娘', look: { hair: '#201818', cloth: '#e88aa8', gender: 'f', bun: 1 },
        lines: ['山徑上的字妖看得見，想避開就繞路走吧。', '周敦頤〈愛蓮說〉說，蓮是「花之君子者也」。'] },
      tip6: { name: '老學究', look: { hair: '#c0c0c0', cloth: '#5a5a7a', beard: 1, cap: '#303030' },
        lines: ['這是藏書閣，下一章才會開放。'] },
      trainerA: { kind: 'trainer', name: '遊學書生', look: { hair: '#2a2a2a', cloth: '#88a0b8', style: 'literati' },
        foe: { lv: 4, hpMul: 1.3, weak: ['字形'], moves: [['吟哦', ['詩詞'], 40], ['考據', ['常識'], 40]] }, reward: 150,
        intro: '兄台留步！以文會友，請！', win: '佩服佩服！在下甘拜下風。', after: '「己所不欲，勿施於人」，此乃恕道也。' },
      trainerB: { kind: 'trainer', name: '江上漁翁', look: { hair: '#c0c0c0', cloth: '#6a8a6a', beard: 1, hat: '#c8b070' },
        foe: { lv: 5, hpMul: 1.4, weak: ['詩詞'], moves: [['漁歌', ['詩詞'], 45], ['撒網', ['成語'], 45]] }, reward: 220,
        intro: '小娃兒，陪老漢過兩招！', win: '長江後浪推前浪啊！', after: '張繼〈楓橋夜泊〉「江楓漁火對愁眠」，說的就是我們漁家的燈火。' },
      questGiver: { kind: 'quest', name: '山中樵夫', look: { hair: '#3a2a20', cloth: '#8a6a4a', hat: '#c8b070' },
        offer: '山徑上的「錯字蟲」咬壞了我的柴擔……能幫我除掉 3 隻嗎？', progress: '還差幾隻呢，牠們常躲在草叢裡。', done: '多謝！這點心意請收下。', after: '山徑清靜多了。' },
      rival: { kind: 'rival', name: '同窗 沈墨', look: { hair: '#1a1a24', cloth: '#e8e0c8', cloth2: '#4a3a6a', style: 'literati' },
        foe: { lv: 6, hpMul: 1.6, weak: ['文言'], moves: [['對句', ['詩詞'], 45], ['駁論', ['常識'], 50]] }, reward: 300,
        intro: '{name}兄，聽說山長把{weapon}給了你？\n\n同窗三年，今日便一較高下！', win: '……佩服。改日再來討教。', after: '我不會輸第二次的。' },
      gym1: { kind: 'gym', name: '詩仙 李白', badge: '詩仙印', badgeColor: '#6a48b8', reward: 600, rewardWeapon: 'seal',
        look: { hair: '#202028', cloth: '#f0f0f8', cloth2: '#7a58c8', style: 'literati' },
        foe: { lv: 8, hpMul: 2.2, weak: ['字形'], cats: ['詩詞', '常識'], moves: [['將進酒', ['詩詞'], 50], ['靜夜思', ['詩詞'], 50], ['謫仙詩', ['詩詞', '常識'], 65]] },
        intro: '哈哈！「天生我材必有用」！小友，陪我對幾句詩如何？\n\n本關考「詩詞」與「文學常識」！',
        win: '好！好！「桃花潭水深千尺」，也不及我此刻的歡喜！', after: '絕句四句、律詩八句，可別記錯了。' },
      locked2: { name: '五柳先生 陶淵明', look: { hair: '#383838', cloth: '#a8b890', cloth2: '#6a7a50', style: 'literati', beard: 1 },
        lines: ['「採菊東籬下，悠然見南山。」小友，等下一章再來找我吧。（試玩版尚未開放）'] },
      trainerC: { kind: 'trainer', name: '國子監學生', look: { hair: '#202020', cloth: '#5a78a8', style: 'literati' },
        foe: { lv: 7, hpMul: 1.4, weak: ['修辭'], moves: [['策論', ['文言'], 50], ['經義', ['常識'], 50]] }, reward: 400,
        intro: '聽說你要挑戰詩仙？先過我這關！', win: '後生可畏，後生可畏！', after: '「學而不思則罔，思而不學則殆」，你我共勉。' },
      guard: { name: '城門守衛', look: { hair: '#202020', cloth: '#a83838', cloth2: '#d8b040', hat: '#303030' },
        lines: ['北門外是下一章的地界，暫不開放！'] },
      tip4: { name: '茶館掌櫃', look: { hair: '#3a3a3a', cloth: '#8a6a4a', beard: 1 },
        lines: ['詩仙就在西邊的太白詩社前。他出的是詩詞題，但據說他的罩門是「字形」……'] },
      tip5: { name: '說書人', look: { hair: '#505050', cloth: '#5a5a7a', beard: 1, cap: '#303030' },
        lines: ['東市西邊的草叢有比較強的字妖，可以去歷練一番！'] },
    },
    doors: {
      home: { kind: 'home', text: '你回到書院廂房，在書案前小憩片刻。\n\n（氣血全滿了！）' },
      heal: { kind: 'heal', text: '郎中：「來，喝碗湯藥，歇一歇。」' },
      shop: { kind: 'shop', text: '掌櫃：「客官裡面請！」' },
      gymdoor: { kind: 'text', text: '門匾上寫著：「太白詩社」。裡面傳來吟詩與舉杯的聲音。' },
      hall1: { kind: 'text', text: '藏書閣的門上了鎖。（下一章開放）' },
      hall2: { kind: 'text', text: '門匾上寫著：「五柳草堂」。（下一章開放）' },
    },
    signs: { sign_town1: '青蓮書院\n↑ 曲水山徑', sign_route1: '曲水山徑\n↑ 長安東市　↓ 青蓮書院', sign_town2: '長安．東市\n西：太白詩社' },
    gates: { needWeapon: '周山長：「且慢！山徑多字妖，先選一件兵器吧。」', trialEnd: '城門守衛：「北門外暫不開放！」（試玩版到此為止）' },
    ending: ['李白：「字妖之亂的源頭，恐怕在更遠的地方……」', '周山長：「{name}，第一章的試煉，你完成了！」'],
  },

  /* ------------------------------------------------------------------ */
  wuxia: {
    id: 'wuxia', name: '俠客生涯', icon: '⚔️', theme: 'wuxia', style: 'wuxia', money: '銀兩',
    tagline: '仗劍走江湖！以文入武，擊退亂字門！',
    focus: '第一章：字音字形',
    chapterName: '第一章．初入江湖',
    mapNames: { town1: '落霞鎮', route1: '竹林小徑', town2: '武林城' },
    music: { town: 'town_wuxia', route: 'route' },
    surnames: ['慕容', '上官', '司徒', '歐陽', '南宮', '沈', '葉', '江', '楚', '燕', '蕭', '顧'],
    given: ['雲', '雪', '風', '影', '寒', '青', '霜', '翎', '驚鴻', '無塵', '長歌', '飛羽'],
    titleLabel: '江湖名號',
    genTitle() { return pick(['追風', '踏雪', '青衫', '無影', '醉月', '驚雷', '寒江', '流星', '白衣', '孤鴻']) + pick(['劍客', '刀客', '少俠', '俠女', '遊俠', '書劍客']); },
    weapons: {
      brush: ['判官筆', '以筆為兵，專點錯字的穴道。'], tome: ['青鋒劍', '劍身刻著成語，招招有典故。'],
      scroll: ['七弦琴', '琴音化為詩詞與古文的劍氣。'], fan: ['鐵骨扇', '扇開扇合之間盡是修辭。'],
      seal: ['袖裡箭', '暗器之術，考驗見聞與眼力。'], legend: ['龍泉劍', '傳說中的神兵，萬法歸一。'] },
    items: { heal: '金創藥', heal2: '大還丹', wenqi: '提神丹', hint: '錦囊' },
    prologue: [
      '江湖之中有一種傳說——修練文字的人，能讓兵器發揮真正的力量。',
      '如今神秘的「亂字門」四處作亂，把詞靈煉成了邪惡的「字妖」，擾亂天下武學秘笈。',
      '{name}，你是落霞鎮初出茅廬的少俠。拿起兵器，行俠仗義吧！',
      '先去鎮上找師父。'],
    roles: {
      mentor: { kind: 'mentor', name: '白眉師父', look: { hair: '#e8e8e8', cloth: '#6a6a78', beard: 1, style: 'wuxia', band: '#8a8a98' },
        intro: '徒兒{name}！習武先習文，秘笈看不懂，武功也練不成。\n\n為師這裡有三件兵器，挑一件吧！',
        later: '來，為師替你運功療傷……好了！' },
      tip1: { name: '客棧小二', look: { hair: '#2a2a2a', cloth: '#c8b890', hat: '#f8f8f8' },
        lines: ['客官，江湖人講究「一諾千金」——說出口的話可要算話！'] },
      tip2: { name: '賣藝姑娘', look: { hair: '#201818', cloth: '#d85868', gender: 'f', style: 'wuxia', band: '#f8d040' },
        lines: ['竹林裡的字妖看得見，不想打就繞路。', '按 START（Enter）打開選單，可以隨時更換兵器。'] },
      tip6: { name: '鏢局夥計', look: { hair: '#2a2020', cloth: '#a84040', style: 'wuxia' },
        lines: ['這是鏢局，總鏢頭出遠門了，下一章才回來。'] },
      trainerA: { kind: 'trainer', name: '江湖刀客', look: { hair: '#2a2020', cloth: '#6a5040', style: 'wuxia' },
        foe: { lv: 4, hpMul: 1.3, weak: ['詞義'], moves: [['狂刀', ['字形'], 40], ['刀鳴', ['字音'], 40]] }, reward: 150,
        intro: '看刀！……不對，看題！', win: '在下佩服！', after: '行走江湖，字要認得準，才不會被騙！' },
      trainerB: { kind: 'trainer', name: '蒙面女俠', look: { hair: '#101010', cloth: '#303848', gender: 'f', style: 'wuxia', band: '#303848' },
        foe: { lv: 5, hpMul: 1.4, weak: ['字音'], moves: [['柳葉鏢', ['詞義'], 45], ['迷蹤步', ['成語'], 45]] }, reward: 220,
        intro: '竹林是我的地盤，想過去就先贏我！', win: '哼，算你有兩下子。', after: '「差強人意」是還算滿意，別用錯了。' },
      questGiver: { kind: 'quest', name: '竹林隱士', look: { hair: '#d0d0d0', cloth: '#6a8a6a', beard: 1, hat: '#c8b070' },
        offer: '竹林裡的「錯字蟲」擾我清修……少俠可否替我除去 3 隻？', progress: '還有幾隻，多在草叢中。', done: '善哉！這些丹藥贈予少俠。', after: '竹林終於清靜了。' },
      rival: { kind: 'rival', name: '師兄 葉孤舟', look: { hair: '#1a1a24', cloth: '#e8e0d0', cloth2: '#3a5a8a', style: 'wuxia', band: '#3a5a8a' },
        foe: { lv: 6, hpMul: 1.6, weak: ['成語'], moves: [['孤舟劍', ['字形'], 45], ['橫江', ['字音'], 50]] }, reward: 300,
        intro: '{name}，師父竟把{weapon}傳給了你？\n\n讓我試試你的斤兩！', win: '哼，算你運氣好。下次可沒這麼簡單。', after: '我會變得更強的。' },
      gym1: { kind: 'gym', name: '峨嵋派 靜月師太', badge: '峨嵋令', badgeColor: '#d07a1a', reward: 600, rewardWeapon: 'seal',
        look: { hair: '#f0f0f0', cloth: '#c8c8d0', cloth2: '#6a6a78', gender: 'f', hat: '#6a6a78' },
        foe: { lv: 8, hpMul: 2.2, weak: ['修辭'], cats: ['字音', '字形'], moves: [['峨嵋刺', ['字形'], 50], ['清音掌', ['字音'], 50], ['金頂佛光', ['字音', '字形'], 65]] },
        intro: '峨嵋心法，首重一個「正」字。字音字形若有一絲偏差，劍招便會走樣！\n\n本派考「字音」與「字形」！',
        win: '好個少俠，心正則字正。', after: '練字如練劍，一筆一畫都不能馬虎。' },
      locked2: { name: '少林寺 慧明大師', look: { hair: '#f0c8a0', skin: '#f0c8a0', cloth: '#e0a030', cloth2: '#b83028', robe: 1 },
        lines: ['阿彌陀佛。施主，下一章再來切磋吧。（試玩版尚未開放）'] },
      trainerC: { kind: 'trainer', name: '丐幫弟子', look: { hair: '#5a4030', cloth: '#8a7a5a', style: 'wuxia', band: '#6a5a3a' },
        foe: { lv: 7, hpMul: 1.4, weak: ['字形'], moves: [['打狗棒', ['閱讀'], 50], ['降龍掌', ['修辭'], 50]] }, reward: 400,
        intro: '打狗棒法……不，打題棒法來了！', win: '嘿嘿，江湖果然藏龍臥虎。', after: '「時間就是金錢」是譬喻法中的暗喻喔。' },
      guard: { name: '城門守衛', look: { hair: '#202020', cloth: '#f0f0f0', cloth2: '#5a78a8', style: 'wuxia', band: '#5a78a8' },
        lines: ['北邊的山路尚未開放！'] },
      tip4: { name: '鏢局鏢師', look: { hair: '#2a2020', cloth: '#a84040', style: 'wuxia' },
        lines: ['靜月師太就在城西。她考字音字形，但聽說她的罩門是「修辭」……竹林的寶箱裡好像藏著一把鐵骨扇。'] },
      tip5: { name: '酒館老闆娘', look: { hair: '#301818', cloth: '#c85a7a', gender: 'f', bun: 1 },
        lines: ['城西草叢的字妖比較兇，可以去那裡磨練！'] },
    },
    doors: {
      home: { kind: 'home', text: '你回到客棧廂房，打坐調息了一會兒。\n\n（氣血全滿了！）' },
      heal: { kind: 'heal', text: '郎中：「少俠受傷了？快服下這帖藥！」' },
      shop: { kind: 'shop', text: '老闆：「少俠要買些什麼？童叟無欺！」' },
      gymdoor: { kind: 'text', text: '門口掛著：「峨嵋派　武林城分舵」。' },
      hall1: { kind: 'text', text: '鏢局大門緊閉。（下一章開放）' },
      hall2: { kind: 'text', text: '門口掛著：「少林寺別院」。（下一章開放）' },
    },
    signs: { sign_town1: '落霞鎮\n↑ 竹林小徑', sign_route1: '竹林小徑\n↑ 武林城　↓ 落霞鎮', sign_town2: '武林城\n西：峨嵋派分舵' },
    gates: { needWeapon: '白眉師父：「站住！竹林裡字妖出沒，先挑件兵器！」', trialEnd: '城門守衛：「北邊的山路尚未開放！」（試玩版到此為止）' },
    ending: ['靜月師太：「亂字門的蹤跡，指向更遠的地方……」', '白眉師父：「好徒兒，第一章的歷練，你完成了！」'],
  },
};
const WORLD_ORDER = ['school', 'literati', 'wuxia'];
