'use strict';
/* =====================================================================
   三種世界觀（試玩版：第一章）
   劇情文字目前為暫定版本，系統與介面確定後再補完整劇情。
   {name} 玩家名字　{weapon} 目前武器名稱
   ===================================================================== */
const WORLDS = {
  /* ------------------------------------------------------------------ */
  school: {
    id: 'school', name: '國中生涯', icon: '🏫', theme: 'school', style: 'school', money: '積分',
    tagline: '在青嵐國中拿起文具，迎戰把課本弄亂的文具妖！',
    focus: '第一章：字音字形',
    chapterName: '第一章．錯字大作戰',
    mapNames: { town1: '青嵐國中．前庭', route1: '後山步道', town2: '藝文中庭', gym1: '字音字形關', home: '我的家', clinic: '保健室', store: '福利社' },
    music: { town: 'town_school', route: 'route' },
    surnames: '陳林黃張李王吳劉蔡楊許鄭謝郭洪'.split(''),
    given: ['宇翔', '品妍', '子晴', '柏睿', '語彤', '承恩', '詠晴', '冠宇', '芷若', '家豪', '思妤', '亦辰', '沛涵', '宥廷', '欣妤', '睿哲'],
    titleLabel: '班級社團',
    genTitle() { return `${pick(['七', '八', '九'])}年${pick(['一', '二', '三', '五', '六', '八'])}班．${pick(['文學社', '圖書股長', '國文小老師', '朗讀社', '書法社', '辯論社'])}`; },
    weapons: {
      brush: ['自動鉛筆', '筆芯削得尖尖的，專門修正錯字與錯音。'], tome: ['成語字典', '厚厚一本，翻到哪一頁都是典故。'],
      scroll: ['國文課本', '翻開就能召喚古文與詩詞的力量。'], fan: ['彩色螢光筆', '畫重點專用，擅長看穿修辭。'],
      seal: ['放大鏡', '看清每個細節，擅長常識與閱讀。'], legend: ['金牌鋼筆', '傳說中會考滿分學長留下的鋼筆。'] },
    items: { heal: '運動飲料', heal2: '營養便當', wenqi: '提神巧克力', hint: '錦囊小抄', atkup: '專注口香糖', defup: '護身護腕', dodgeup: '體育課球鞋', cure: '保健室藥包' },
    monsters: { brush: '鉛筆妖', tome: '字典妖', scroll: '課本妖', fan: '螢光筆妖', seal: '放大鏡妖', legend: '鋼筆妖' }, monSuffix: '妖',
    guardians: { a: 'g_pen', b: 'g_paper' }, routeNames: { a: '同心之路', b: '競逐之路' },
    routeEnd: { a: '程昊：「以後的路，我們一起走吧！」', b: '程昊：「下一章，我一定會超越你！」' },
    gymName: '字音字形關',
    intro: [
      '你將成為青嵐國中的一名新生。',
      '傳說每個文字裡都住著「詞靈」。最近詞靈被錯字的力量汙染，附在文具上，變成了到處搗亂的「文具妖」！',
      '拿起你的文具當武器，打倒文具妖、收集碎片、打造更強的武器，挑戰校園裡的關主吧！'],
    start: '{name}的國中生活，從這裡開始！先去前庭找國文老師——王老師。',
    roles: {
      mentor: { kind: 'mentor', name: '王老師', look: { hair: '#2a2a30', cloth: '#5a7ab0', pants: '#3a3a48', glasses: 1 },
        intro: '早安，{name}！文具妖越來越多了，你願意幫忙嗎？\n\n這三件文具都藏著國文的力量，挑一件當你的武器吧！',
        practice: '好，我們到後山步道入口練習吧！城鎮裡不能打鬥喔。',
        later: '累了嗎？讓老師幫你恢復一下精神……好了，加油！' },
      homeNpc: { kind: 'healer', name: '媽媽', look: { hair: '#4a3020', cloth: '#e88a8a', gender: 'f', bun: 1 }, text: '媽媽：「要出門啦？別忘了帶聯絡簿！先休息一下吧。」' },
      healer: { kind: 'healer', name: '保健室阿姨', look: { hair: '#3a2a20', cloth: '#f8f8f8', cloth2: '#e88aa8', gender: 'f', hat: '#f8f8f8' }, text: '保健室阿姨：「受傷了嗎？來，休息一下！」' },
      clerk: { kind: 'shop', name: '福利社阿姨', look: { hair: '#5a3a2a', cloth: '#f0d050', gender: 'f' }, text: '福利社阿姨：「歡迎光臨！要買點什麼？」' },
      tip1: { name: '同學 阿哲', look: { hair: '#402818', cloth: '#f8f8f8', cloth2: '#3a58a0', style: 'school' },
        lines: ['「再接再厲」的「厲」通「礪」，是「磨利」的意思喔！'] },
      tip2: { name: '學姊 小雯', look: { hair: '#201818', cloth: '#f8f8f8', cloth2: '#3a58a0', gender: 'f', style: 'school' },
        lines: ['步道上的文具妖看得見喔！不想打的話，繞過去就好。', '打倒文具妖有機會掉「碎片」，集滿 5 片就能在選單的「鍛造」合成新武器！'] },
      tip6: { name: '工友伯伯', look: { hair: '#909090', cloth: '#6a8a6a', hat: '#4a6a4a' },
        lines: ['這棟是舊禮堂，還在整修中，下一章才會開放喔。'] },
      trainerA: { kind: 'trainer', name: '七年級 阿胖', look: { hair: '#3a2a20', cloth: '#f8f8f8', cloth2: '#3a58a0', style: 'school', bag: '#3a8a48' },
        foe: { lv: 4, hpMul: 1.3, weak: ['詞義'], moves: [['注音飛彈', ['字音'], 40], ['錯字連發', ['字形'], 40]] }, reward: 150,
        intro: '嘿！我們的眼神對上了，來一場國文對決吧！', win: '哇，你好厲害……我回去多背幾個注音！', after: '「躊躇」念作ㄔㄡˊ ㄔㄨˊ，我終於記住了。' },
      trainerB: { kind: 'trainer', name: '八年級 小芸', look: { hair: '#5a3020', cloth: '#f8f8f8', cloth2: '#3a58a0', gender: 'f', style: 'school', bag: '#8a58c8' },
        foe: { lv: 5, hpMul: 1.4, weak: ['字音'], moves: [['詞語陷阱', ['詞義'], 45], ['成語考驗', ['成語'], 45]] }, reward: 220,
        intro: '新生？學姊來考考你！', win: '不錯嘛，基本功很扎實！', after: '「差強人意」是「大致令人滿意」，不是「很差」喔！' },
      questGiver: { kind: 'quest', name: '巡山伯伯', look: { hair: '#909090', cloth: '#6a8a6a', hat: '#c8a860' },
        offer: '步道上的「{mon}」越來越多了……可以幫我消滅 3 隻嗎？', progress: '還差一點喔！{mon}通常躲在草叢裡。', done: '太感謝了！這些給你，路上小心。', after: '步道乾淨多了，謝謝你！' },
      rival: { kind: 'rival', name: '同班同學 程昊', look: { hair: '#1a1a24', cloth: '#f8f8f8', cloth2: '#c83838', style: 'school', bag: '#303038' },
        foe: { lv: 6, hpMul: 1.6, weak: ['成語'], moves: [['快問快答', ['字音', '字形'], 45], ['搶答', ['詞義'], 50]] }, reward: 300,
        intro: '喂，{name}！聽說你拿到了{weapon}？\n\n別以為這樣就能當英雄。來比比看，誰才是班上最強的！', win: '可惡……下次我一定會贏！', after: '我先去練功了，別太得意！',
        choice: { q: '程昊咬著嘴唇：「……可惡，我是不是很遜？」\n\n你要怎麼回答？', opts: ['「一起讀書吧！下次換你教我。」', '「下次再來挑戰我，我等你！」'], replies: ['……真的嗎？好，那就說定了！', '哼，你等著，我一定會追上你！'] },
        afterA: '我們一起加油吧！我先去中庭幫你打聽關主的弱點！', afterB: '下次我不會輸！我要先去關卡那邊觀察。' },
      rivalA: { name: '同班同學 程昊', look: { hair: '#1a1a24', cloth: '#f8f8f8', cloth2: '#c83838', style: 'school', bag: '#303038' },
        lines: ['{name}！我整理了關主的筆記：林小晴最怕「修辭」題，記得帶螢光筆！', '讀書有伴，果然比較有動力！'] },
      rivalB: { name: '同班同學 程昊', look: { hair: '#1a1a24', cloth: '#f8f8f8', cloth2: '#c83838', style: 'school', bag: '#303038' },
        lines: ['我是來觀察關主弱點的……才不是在等你！', '聽好了，她好像很怕「修辭」題。我只說一次！'] },
      gym1: { kind: 'gym', name: '風紀股長 林小晴', badge: '字形徽章', badgeColor: '#d07a1a', reward: 600, rewardWeapon: 'seal',
        look: { hair: '#181820', cloth: '#f8f8f8', cloth2: '#c83838', gender: 'f', style: 'school', bag: '#c83838' },
        foe: { lv: 8, hpMul: 2.2, weak: ['修辭'], cats: ['字音', '字形'], moves: [['紅筆訂正', ['字形'], 50], ['注音審判', ['字音'], 50], ['錯字全殲', ['字音', '字形'], 65]] },
        intro: '我是風紀股長林小晴！錯字、錯音，一個都別想逃過我的眼睛！\n\n本關考「字音」與「字形」，準備好了嗎？',
        win: '……你的字音字形功力，我服了。', after: '形近字要從部首判斷意思，例如「睫」有目字旁，所以是「迫在眉睫」。' },
      locked2: { name: '成語社社長 吳大明', look: { hair: '#2a2a2a', cloth: '#f8f8f8', cloth2: '#3a58a0', style: 'school', glasses: 1 },
        lines: ['我是成語社社長吳大明。等第二章開放，我們再來一決高下！（試玩版尚未開放）'] },
      trainerC: { kind: 'trainer', name: '九年級 學長阿傑', look: { hair: '#1a1a20', cloth: '#f8f8f8', cloth2: '#3a58a0', style: 'school', bag: '#303038' },
        foe: { lv: 7, hpMul: 1.4, weak: ['字形'], moves: [['會考題', ['閱讀'], 50], ['修辭攻勢', ['修辭'], 50]] }, reward: 400,
        intro: '會考倒數中！陪我練練手吧！', win: '你這實力，會考穩了！', after: '「時間就是金錢」用的是譬喻中的「暗喻」，喻詞是「是」。' },
      guard: { name: '糾察隊員', look: { hair: '#202020', cloth: '#f8f8f8', cloth2: '#d8b020', style: 'school', hat: '#d8b020' },
        lines: ['北邊是往第二章的路，目前還在施工中！'] },
      tip4: { name: '圖書館志工', look: { hair: '#6a3a2a', cloth: '#58a888', gender: 'f' },
        lines: ['風紀股長在西邊的「字音字形關」裡。她只出「字音」和「字形」題，但聽說她不太擅長「修辭」……步道上的寶箱裡好像有螢光筆喔！'] },
      tip5: { name: '美術班同學', look: { hair: '#c86a3a', cloth: '#f8f8f8', cloth2: '#3a58a0', gender: 'f', style: 'school', bag: '#e86ab0' },
        lines: ['等級不夠的話，回後山步道多打幾隻文具妖吧！'] },
      gymguide: { name: '關卡志工', look: { hair: '#303030', cloth: '#f8f8f8', cloth2: '#c83838', style: 'school' },
        lines: ['這裡是「字音字形關」，關主是風紀股長林小晴。準備好了就走進門裡挑戰吧！'] },
      smith: { kind: 'smith', name: '工藝老師', look: { hair: '#4a3a2a', cloth: '#6a7a8a', glasses: 1 },
        lines: ['我是工藝老師。碎片合成、武器升階都可以找我，也可以在選單的「鍛造」自己來喔！'] },
    },
    doors: {
      home: { kind: 'home', text: '媽媽：「要出門啦？別忘了帶聯絡簿！」\n\n（在家休息了一下，氣血全滿了！）' },
      heal: { kind: 'heal', text: '保健室阿姨：「受傷了嗎？來，休息一下！」' },
      shop: { kind: 'shop', text: '福利社阿姨：「歡迎光臨！要買點什麼？」' },
      gymdoor: { kind: 'text', text: '門上貼著：「字音字形關　關主：風紀股長 林小晴」' },
      hall1: { kind: 'text', text: '舊禮堂的門上了鎖。（下一章開放）' },
      hall2: { kind: 'text', text: '門上貼著：「成語社」。（下一章開放）' },
    },
    signs: { sign_town1: '青嵐國中．前庭\n↑ 後山步道', sign_route1: '後山步道\n↑ 藝文中庭　↓ 前庭', sign_town2: '藝文中庭\n西：字音字形關' },
    gates: { needWeapon: '王老師：「等等！{name}，步道上有文具妖，先來選一件武器吧！」', trialEnd: '糾察隊員：「前面是第二章的路，還在施工中！」（試玩版到此為止）' },
    ending: ['林小晴：「文具妖的源頭，好像在學校更深的地方……」', '王老師：「{name}，第一章的挑戰，你完成了！」'],
  },

  /* ------------------------------------------------------------------ */
  literati: {
    id: 'literati', name: '文人墨客生涯', icon: '🖌️', theme: 'literati', style: 'literati', money: '文',
    tagline: '執筆為劍，在翰墨大陸向詩仙李白請益！',
    focus: '第一章：詩詞與常識',
    chapterName: '第一章．詩仙醉月',
    mapNames: { town1: '青蓮書院', route1: '曲水山徑', town2: '長安．東市', gym1: '太白詩社', home: '書院廂房', clinic: '醫館', store: '文房四寶鋪' },
    music: { town: 'town_literati', route: 'route' },
    surnames: '李蘇王謝沈柳顧韓陸杜白范'.split(''),
    given: ['清', '雲', '翰', '墨', '青', '硯', '詠', '瑾', '書', '竹', '懷瑾', '子衿', '若水', '遠山', '聽雨', '采薇'],
    titleLabel: '字號',
    genTitle() { return `字${pick(['子', '伯', '仲', '季', '文', '德'])}${pick(['瞻', '安', '遠', '思', '明', '修', '然', '和'])}，號${pick(['青竹', '聽松', '臨江', '望月', '南山', '墨池', '聽雨', '清溪'])}${pick(['居士', '散人', '先生', '山人'])}`; },
    weapons: {
      brush: ['狼毫筆', '筆鋒剛勁，一點一畫都能辨正字形字音。'], tome: ['竹簡', '刻滿成語典故的古老竹簡。'],
      scroll: ['玉笛', '吹奏時會浮現古詩與古文。'], fan: ['宣紙扇', '扇面題滿詩句，擅長修辭。'],
      seal: ['端硯', '名硯之首，研出的墨能增長見聞。'], legend: ['松煙古墨', '傳說中文曲星留下的古墨。'] },
    items: { heal: '參茶', heal2: '靈芝', wenqi: '墨香', hint: '錦囊', atkup: '狼毫新鋒', defup: '青玉鎮紙', dodgeup: '輕羅衣', cure: '清心散' },
    monsters: { brush: '筆精', tome: '竹簡精', scroll: '玉笛精', fan: '紙扇精', seal: '硯精', legend: '古墨精' }, monSuffix: '精',
    guardians: { a: 'g_pen', b: 'g_paper' }, routeNames: { a: '知音之路', b: '爭鳴之路' },
    routeEnd: { a: '沈墨：「高山流水，知音難覓。有你同行，此生無憾。」', b: '沈墨：「百家爭鳴，方見真章。下回，我必勝你！」' },
    gymName: '太白詩社',
    intro: [
      '你將成為青蓮書院的一名學子，來到古今文人齊聚的「翰墨大陸」。',
      '近來文曲星光黯淡，詞靈受墨氣所染，附在文房之寶上，化為作亂的「文房精怪」。',
      '執筆為劍，降伏精怪、收集碎片、鍛造兵器，向詩仙李白請益吧！'],
    start: '{name}的求學之路，從青蓮書院開始。先去拜見周山長。',
    roles: {
      mentor: { kind: 'mentor', name: '周山長', look: { hair: '#d8d8d8', cloth: '#6a5a8a', beard: 1, style: 'literati' },
        intro: '學子{name}，來得正好。「工欲善其事，必先利其器」。\n\n這三件文房之寶，選一件作你的兵器吧。',
        practice: '書院之內不宜動武。隨老夫到山徑入口，演練一番。',
        later: '來，老夫替你調息片刻……好了，去吧！' },
      homeNpc: { kind: 'healer', name: '書院嬤嬤', look: { hair: '#909090', cloth: '#8a7a9a', gender: 'f', bun: 1 }, text: '書院嬤嬤：「讀書辛苦了，喝碗熱湯歇一歇。」' },
      healer: { kind: 'healer', name: '郎中', look: { hair: '#c0c0c0', cloth: '#5a7a6a', beard: 1, cap: '#303030' }, text: '郎中：「來，喝碗湯藥，歇一歇。」' },
      clerk: { kind: 'shop', name: '掌櫃', look: { hair: '#3a3a3a', cloth: '#8a6a4a', cap: '#303030' }, text: '掌櫃：「客官裡面請！筆墨紙硯樣樣俱全！」' },
      tip1: { name: '書僮 小硯', look: { hair: '#2a2a2a', cloth: '#6a9ac8', style: 'literati', bun: 1 },
        lines: ['文房四寶是筆、墨、紙、硯。書院裡的兵器，都是從文房四寶變來的呢！'] },
      tip2: { name: '賣花姑娘', look: { hair: '#201818', cloth: '#e88aa8', gender: 'f', bun: 1 },
        lines: ['山徑上的精怪看得見，想避開就繞路走吧。', '打倒精怪有時會掉落「碎片」，集滿 5 片便能鍛造兵器喔！'] },
      tip6: { name: '老學究', look: { hair: '#c0c0c0', cloth: '#5a5a7a', beard: 1, cap: '#303030' },
        lines: ['這是藏書閣，下一章才會開放。'] },
      trainerA: { kind: 'trainer', name: '遊學書生', look: { hair: '#2a2a2a', cloth: '#88a0b8', style: 'literati' },
        foe: { lv: 4, hpMul: 1.3, weak: ['字形'], moves: [['吟哦', ['詩詞'], 40], ['考據', ['常識'], 40]] }, reward: 150,
        intro: '兄台留步！以文會友，請！', win: '佩服佩服！在下甘拜下風。', after: '「己所不欲，勿施於人」，此乃恕道也。' },
      trainerB: { kind: 'trainer', name: '江上漁翁', look: { hair: '#c0c0c0', cloth: '#6a8a6a', beard: 1, hat: '#c8b070' },
        foe: { lv: 5, hpMul: 1.4, weak: ['詩詞'], moves: [['漁歌', ['詩詞'], 45], ['撒網', ['成語'], 45]] }, reward: 220,
        intro: '小娃兒，陪老漢過兩招！', win: '長江後浪推前浪啊！', after: '張繼〈楓橋夜泊〉「江楓漁火對愁眠」，說的就是我們漁家的燈火。' },
      questGiver: { kind: 'quest', name: '山中樵夫', look: { hair: '#3a2a20', cloth: '#8a6a4a', hat: '#c8b070' },
        offer: '山徑上的「{mon}」弄壞了我的柴擔……能幫我除掉 3 隻嗎？', progress: '還差幾隻呢，{mon}常躲在草叢裡。', done: '多謝！這點心意請收下。', after: '山徑清靜多了。' },
      rival: { kind: 'rival', name: '同窗 沈墨', look: { hair: '#1a1a24', cloth: '#e8e0c8', cloth2: '#4a3a6a', style: 'literati' },
        foe: { lv: 6, hpMul: 1.6, weak: ['文言'], moves: [['對句', ['詩詞'], 45], ['駁論', ['常識'], 50]] }, reward: 300,
        intro: '{name}兄，聽說山長把{weapon}給了你？\n\n同窗三年，今日便一較高下！', win: '……佩服。改日再來討教。', after: '我不會輸第二次的。',
        choice: { q: '沈墨長嘆：「今日技不如人……你我之間，該當如何？」\n\n你要怎麼回答？', opts: ['「以詩會友，你我結為知己！」', '「文章千古事，各自努力吧！」'], replies: ['好！得一知己，足矣！', '說得好，改日必再討教！'] },
        afterA: '知己在側，何懼詩仙？我先去東市替你打聽。', afterB: '我先去詩社一探虛實，你好自為之。' },
      rivalA: { name: '同窗 沈墨', look: { hair: '#1a1a24', cloth: '#e8e0c8', cloth2: '#4a3a6a', style: 'literati' },
        lines: ['{name}兄！聽說詩仙的罩門是「字形」，帶上筆吧！', '有知己同行，這一路便不寂寞了。'] },
      rivalB: { name: '同窗 沈墨', look: { hair: '#1a1a24', cloth: '#e8e0c8', cloth2: '#4a3a6a', style: 'literati' },
        lines: ['……我先來看看詩仙的深淺。', '他似乎不擅長「字形」題，你好自為之。'] },
      gym1: { kind: 'gym', name: '詩仙 李白', badge: '詩仙印', badgeColor: '#6a48b8', reward: 600, rewardWeapon: 'seal',
        look: { hair: '#202028', cloth: '#f0f0f8', cloth2: '#7a58c8', style: 'literati' },
        foe: { lv: 8, hpMul: 2.2, weak: ['字形'], cats: ['詩詞', '常識'], moves: [['將進酒', ['詩詞'], 50], ['靜夜思', ['詩詞'], 50], ['謫仙詩', ['詩詞', '常識'], 65]] },
        intro: '哈哈！「天生我材必有用」！小友，陪我對幾句詩如何？\n\n本關考「詩詞」與「文學常識」！',
        win: '好！好！「桃花潭水深千尺」，也不及我此刻的歡喜！', after: '絕句四句、律詩八句，可別記錯了。' },
      locked2: { name: '五柳先生 陶淵明', look: { hair: '#383838', cloth: '#a8b890', cloth2: '#6a7a50', style: 'literati', beard: 1 },
        lines: ['「採菊東籬下，悠然見南山。」小友，等下一章再來找我吧。（試玩版尚未開放）'] },
      trainerC: { kind: 'trainer', name: '國子監學生', look: { hair: '#202020', cloth: '#5a78a8', style: 'literati' },
        foe: { lv: 7, hpMul: 1.4, weak: ['修辭'], moves: [['策論', ['文言'], 50], ['經義', ['常識'], 50]] }, reward: 400,
        intro: '聽說你要挑戰詩仙？先過我這關！', win: '後生可畏，後生可畏！', after: '「學而不思則罔，思而不學則殆」，你我共勉。' },
      guard: { name: '城門守衛', look: { hair: '#202020', cloth: '#a83838', cloth2: '#d8b040', hat: '#303030' },
        lines: ['北門外是下一章的地界，暫不開放！'] },
      tip4: { name: '茶館掌櫃', look: { hair: '#3a3a3a', cloth: '#8a6a4a', beard: 1 },
        lines: ['詩仙就在西邊的太白詩社裡。他出的是詩詞題，但據說他的罩門是「字形」……'] },
      tip5: { name: '說書人', look: { hair: '#505050', cloth: '#5a5a7a', beard: 1, cap: '#303030' },
        lines: ['功力不足的話，回曲水山徑多歷練幾回吧！'] },
      gymguide: { name: '詩社書童', look: { hair: '#2a2a2a', cloth: '#7a58c8', style: 'literati', bun: 1 },
        lines: ['這裡是「太白詩社」，詩仙正在裡頭飲酒作詩。準備好了就進門吧！'] },
      smith: { kind: 'smith', name: '製筆匠', look: { hair: '#5a4a3a', cloth: '#8a6a4a', beard: 1 },
        lines: ['老朽專製筆墨。碎片合成、兵器升階，都能在選單的「鍛造」辦到。'] },
    },
    doors: {
      home: { kind: 'home', text: '你回到書院廂房，在書案前小憩片刻。\n\n（氣血全滿了！）' },
      heal: { kind: 'heal', text: '郎中：「來，喝碗湯藥，歇一歇。」' },
      shop: { kind: 'shop', text: '掌櫃：「客官裡面請！」' },
      gymdoor: { kind: 'text', text: '門匾上寫著：「太白詩社」。裡面傳來吟詩與舉杯的聲音。' },
      hall1: { kind: 'text', text: '藏書閣的門上了鎖。（下一章開放）' },
      hall2: { kind: 'text', text: '門匾上寫著：「五柳草堂」。（下一章開放）' },
    },
    signs: { sign_town1: '青蓮書院\n↑ 曲水山徑', sign_route1: '曲水山徑\n↑ 長安東市　↓ 青蓮書院', sign_town2: '長安．東市\n西：太白詩社' },
    gates: { needWeapon: '周山長：「且慢！山徑多精怪，先選一件兵器吧。」', trialEnd: '城門守衛：「北門外暫不開放！」（試玩版到此為止）' },
    ending: ['李白：「精怪之亂的源頭，恐怕在更遠的地方……」', '周山長：「{name}，第一章的試煉，你完成了！」'],
  },

  /* ------------------------------------------------------------------ */
  wuxia: {
    id: 'wuxia', name: '俠客生涯', icon: '⚔️', theme: 'wuxia', style: 'wuxia', money: '銀兩',
    tagline: '仗劍走江湖！以文入武，擊退亂字門！',
    focus: '第一章：字音字形',
    chapterName: '第一章．初入江湖',
    mapNames: { town1: '落霞鎮', route1: '竹林小徑', town2: '武林城', gym1: '峨嵋分舵', home: '客棧廂房', clinic: '藥鋪', store: '雜貨鋪' },
    music: { town: 'town_wuxia', route: 'route' },
    surnames: ['慕容', '上官', '司徒', '歐陽', '南宮', '沈', '葉', '江', '楚', '燕', '蕭', '顧'],
    given: ['雲', '雪', '風', '影', '寒', '青', '霜', '翎', '驚鴻', '無塵', '長歌', '飛羽'],
    titleLabel: '江湖名號',
    genTitle() { return pick(['追風', '踏雪', '青衫', '無影', '醉月', '驚雷', '寒江', '流星', '白衣', '孤鴻']) + pick(['劍客', '刀客', '少俠', '俠女', '遊俠', '書劍客']); },
    weapons: {
      brush: ['判官筆', '以筆為兵，專點錯字的穴道。'], tome: ['青鋒劍', '劍身刻著成語，招招有典故。'],
      scroll: ['七弦琴', '琴音化為詩詞與古文的劍氣。'], fan: ['鐵骨扇', '扇開扇合之間盡是修辭。'],
      seal: ['袖裡箭', '暗器之術，考驗見聞與眼力。'], legend: ['龍泉劍', '傳說中的神兵，萬法歸一。'] },
    items: { heal: '金創藥', heal2: '大還丹', wenqi: '提神丹', hint: '錦囊', atkup: '烈酒', defup: '軟蝟甲', dodgeup: '輕功靴', cure: '解毒丹' },
    monsters: { brush: '筆魂', tome: '劍魂', scroll: '琴魂', fan: '扇魂', seal: '箭魂', legend: '龍泉劍魂' }, monSuffix: '魂',
    guardians: { a: 'g_pen', b: 'g_paper' }, routeNames: { a: '俠義之路', b: '孤鴻之路' },
    routeEnd: { a: '葉孤舟：「俠之大者，為國為民。這條路，我陪你走到底！」', b: '葉孤舟：「江湖再見時，勝負還未分呢！」' },
    gymName: '峨嵋分舵',
    intro: [
      '你將成為落霞鎮一名初出茅廬的少俠。',
      '江湖中，神秘的「亂字門」以邪功驅使詞靈附在兵器上，化為作亂的「兵魂」，擾亂天下武學秘笈。',
      '拿起兵器，擊敗兵魂、收集碎片、鍛造神兵，挑戰三派高手吧！'],
    start: '{name}的江湖路，從落霞鎮開始。先去鎮上找師父。',
    roles: {
      mentor: { kind: 'mentor', name: '白眉師父', look: { hair: '#e8e8e8', cloth: '#6a6a78', beard: 1, style: 'wuxia', band: '#8a8a98' },
        intro: '徒兒{name}！習武先習文，秘笈看不懂，武功也練不成。\n\n為師這裡有三件兵器，挑一件吧！',
        practice: '鎮上不可動武。走，到竹林入口，為師陪你練兩招！',
        later: '來，為師替你運功療傷……好了！' },
      homeNpc: { kind: 'healer', name: '客棧老闆娘', look: { hair: '#301818', cloth: '#c85a7a', gender: 'f', bun: 1 }, text: '客棧老闆娘：「少俠回來啦？房間收拾好了，好好歇著。」' },
      healer: { kind: 'healer', name: '藥鋪郎中', look: { hair: '#c0c0c0', cloth: '#6a7a5a', beard: 1 }, text: '郎中：「少俠受傷了？快服下這帖藥！」' },
      clerk: { kind: 'shop', name: '雜貨鋪老闆', look: { hair: '#2a2020', cloth: '#8a6a3a', style: 'wuxia', band: '#6a4a2a' }, text: '老闆：「少俠要買些什麼？童叟無欺！」' },
      tip1: { name: '客棧小二', look: { hair: '#2a2a2a', cloth: '#c8b890', hat: '#f8f8f8' },
        lines: ['客官，江湖人講究「一諾千金」——說出口的話可要算話！'] },
      tip2: { name: '賣藝姑娘', look: { hair: '#201818', cloth: '#d85868', gender: 'f', style: 'wuxia', band: '#f8d040' },
        lines: ['竹林裡的兵魂看得見，不想打就繞路。', '擊敗兵魂有機會掉「碎片」，集滿 5 片就能鍛造新兵器！'] },
      tip6: { name: '鏢局夥計', look: { hair: '#2a2020', cloth: '#a84040', style: 'wuxia' },
        lines: ['這是鏢局，總鏢頭出遠門了，下一章才回來。'] },
      trainerA: { kind: 'trainer', name: '江湖刀客', look: { hair: '#2a2020', cloth: '#6a5040', style: 'wuxia' },
        foe: { lv: 4, hpMul: 1.3, weak: ['詞義'], moves: [['狂刀', ['字形'], 40], ['刀鳴', ['字音'], 40]] }, reward: 150,
        intro: '看刀！……不對，看題！', win: '在下佩服！', after: '行走江湖，字要認得準，才不會被騙！' },
      trainerB: { kind: 'trainer', name: '蒙面女俠', look: { hair: '#101010', cloth: '#303848', gender: 'f', style: 'wuxia', band: '#303848' },
        foe: { lv: 5, hpMul: 1.4, weak: ['字音'], moves: [['柳葉鏢', ['詞義'], 45], ['迷蹤步', ['成語'], 45]] }, reward: 220,
        intro: '竹林是我的地盤，想過去就先贏我！', win: '哼，算你有兩下子。', after: '「差強人意」是還算滿意，別用錯了。' },
      questGiver: { kind: 'quest', name: '竹林隱士', look: { hair: '#d0d0d0', cloth: '#6a8a6a', beard: 1, hat: '#c8b070' },
        offer: '竹林裡的「{mon}」擾我清修……少俠可否替我除去 3 隻？', progress: '還有幾隻，{mon}多在草叢中。', done: '善哉！這些丹藥贈予少俠。', after: '竹林終於清靜了。' },
      rival: { kind: 'rival', name: '師兄 葉孤舟', look: { hair: '#1a1a24', cloth: '#e8e0d0', cloth2: '#3a5a8a', style: 'wuxia', band: '#3a5a8a' },
        foe: { lv: 6, hpMul: 1.6, weak: ['成語'], moves: [['孤舟劍', ['字形'], 45], ['橫江', ['字音'], 50]] }, reward: 300,
        intro: '{name}，師父竟把{weapon}傳給了你？\n\n讓我試試你的斤兩！', win: '哼，算你運氣好。下次可沒這麼簡單。', after: '我會變得更強的。',
        choice: { q: '葉孤舟收劍：「……輸了就是輸了。你打算怎麼做？」\n\n你要怎麼回答？', opts: ['「師兄，我們一起行俠仗義！」', '「江湖路遠，各憑本事！」'], replies: ['……好，這條路，我陪你走！', '哈！好一個各憑本事，後會有期！'] },
        afterA: '我先去武林城替你探路！', afterB: '我去峨嵋分舵等你，別讓我失望。' },
      rivalA: { name: '師兄 葉孤舟', look: { hair: '#1a1a24', cloth: '#e8e0d0', cloth2: '#3a5a8a', style: 'wuxia', band: '#3a5a8a' },
        lines: ['{name}！我打聽到靜月師太的罩門是「修辭」，鐵骨扇派得上用場！', '有人並肩作戰，江湖也沒那麼冷了。'] },
      rivalB: { name: '師兄 葉孤舟', look: { hair: '#1a1a24', cloth: '#e8e0d0', cloth2: '#3a5a8a', style: 'wuxia', band: '#3a5a8a' },
        lines: ['哼，我先來瞧瞧峨嵋的功夫。', '聽說師太的罩門是「修辭」……你自己看著辦。'] },
      gym1: { kind: 'gym', name: '峨嵋派 靜月師太', badge: '峨嵋令', badgeColor: '#d07a1a', reward: 600, rewardWeapon: 'seal',
        look: { hair: '#f0f0f0', cloth: '#c8c8d0', cloth2: '#6a6a78', gender: 'f', hat: '#6a6a78' },
        foe: { lv: 8, hpMul: 2.2, weak: ['修辭'], cats: ['字音', '字形'], moves: [['峨嵋刺', ['字形'], 50], ['清音掌', ['字音'], 50], ['金頂佛光', ['字音', '字形'], 65]] },
        intro: '峨嵋心法，首重一個「正」字。字音字形若有一絲偏差，劍招便會走樣！\n\n本派考「字音」與「字形」！',
        win: '好個少俠，心正則字正。', after: '練字如練劍，一筆一畫都不能馬虎。' },
      locked2: { name: '少林寺 慧明大師', look: { hair: '#f0c8a0', skin: '#f0c8a0', cloth: '#e0a030', cloth2: '#b83028', robe: 1 },
        lines: ['阿彌陀佛。施主，下一章再來切磋吧。（試玩版尚未開放）'] },
      trainerC: { kind: 'trainer', name: '丐幫弟子', look: { hair: '#5a4030', cloth: '#8a7a5a', style: 'wuxia', band: '#6a5a3a' },
        foe: { lv: 7, hpMul: 1.4, weak: ['字形'], moves: [['打狗棒', ['閱讀'], 50], ['降龍掌', ['修辭'], 50]] }, reward: 400,
        intro: '打狗棒法……不，打題棒法來了！', win: '嘿嘿，江湖果然藏龍臥虎。', after: '「時間就是金錢」是譬喻法中的暗喻喔。' },
      guard: { name: '城門守衛', look: { hair: '#202020', cloth: '#f0f0f0', cloth2: '#5a78a8', style: 'wuxia', band: '#5a78a8' },
        lines: ['北邊的山路尚未開放！'] },
      tip4: { name: '鏢局鏢師', look: { hair: '#2a2020', cloth: '#a84040', style: 'wuxia' },
        lines: ['靜月師太就在城西的峨嵋分舵裡。她考字音字形，但聽說她的罩門是「修辭」……竹林的寶箱裡好像藏著一把鐵骨扇。'] },
      tip5: { name: '酒館老闆娘', look: { hair: '#301818', cloth: '#c85a7a', gender: 'f', bun: 1 },
        lines: ['功夫不到家的話，回竹林多練練吧！'] },
      gymguide: { name: '峨嵋弟子', look: { hair: '#101010', cloth: '#c8c8d0', gender: 'f', hat: '#6a6a78' },
        lines: ['這裡是峨嵋分舵，師太就在裡面。要挑戰就進門吧！'] },
      smith: { kind: 'smith', name: '鐵匠', look: { hair: '#2a2020', cloth: '#5a4a3a', style: 'wuxia', band: '#8a6a4a' },
        lines: ['打鐵鑄劍，童叟無欺！碎片合成、兵器升階，在選單的「鍛造」就能辦。'] },
    },
    doors: {
      home: { kind: 'home', text: '你回到客棧廂房，打坐調息了一會兒。\n\n（氣血全滿了！）' },
      heal: { kind: 'heal', text: '郎中：「少俠受傷了？快服下這帖藥！」' },
      shop: { kind: 'shop', text: '老闆：「少俠要買些什麼？童叟無欺！」' },
      gymdoor: { kind: 'text', text: '門口掛著：「峨嵋派　武林城分舵」。' },
      hall1: { kind: 'text', text: '鏢局大門緊閉。（下一章開放）' },
      hall2: { kind: 'text', text: '門口掛著：「少林寺別院」。（下一章開放）' },
    },
    signs: { sign_town1: '落霞鎮\n↑ 竹林小徑', sign_route1: '竹林小徑\n↑ 武林城　↓ 落霞鎮', sign_town2: '武林城\n西：峨嵋派分舵' },
    gates: { needWeapon: '白眉師父：「站住！竹林裡兵魂出沒，先挑件兵器！」', trialEnd: '城門守衛：「北邊的山路尚未開放！」（試玩版到此為止）' },
    ending: ['靜月師太：「亂字門的蹤跡，指向更遠的地方……」', '白眉師父：「好徒兒，第一章的歷練，你完成了！」'],
  },
};
const WORLD_ORDER = ['school', 'literati', 'wuxia'];

/* =====================================================================
   國中生涯．獨立劇情（依〈國中生涯劇情〉）
   目標：打倒五位被「升學焦慮（墨塵）」附身的館主，找回五片准考證碎片。
   ===================================================================== */
(() => {
  const S = WORLDS.school;
  const stu = (hair, c2, extra) => Object.assign({ hair, cloth: '#f8f8f8', cloth2: c2, style: 'school' }, extra || {});
  S.story = true;
  S.start = { map: 'c8', x: 3, y: 3, dir: 'up' };
  S.homeTown = { map: 'chendu', x: 11, y: 7 };     // 一定要是走得過去的格子（舊的 16,11 是稻田）
  S.tagline = '找回被墨塵奪走的五片准考證碎片，堂堂正正走進考場！';
  S.fragName = '准考證碎片';
  S.stages = [
    { name: '第一道館．注音坡', text: '沿著通學小徑往北到「注音坡」，挑戰道館①的字音字形小老師。', roles: ['boss1'], tiles: [['chendu', 7, 15], ['r1', 3, 16]] },
    { name: '第二道館．典籍港', text: '經過抄書巷前往「典籍港」，挑戰道館②的成語圖書股長。', roles: ['rival1', 'boss2'], tiles: [['zhuyin', 12, 15], ['r2', 17, 15], ['chaoshu', 13, 17], ['r3', 17, 15]] },
    { name: '第三道館．花南街', text: '走聲音鐘步道（記得幫忙分組報告）前往「花南街」，挑戰道館③。', roles: ['m1', 'm2', 'm3', 'boss3'], tiles: [['dianji', 13, 16], ['r4', 17, 15]] },
    { name: '第四道館．碑林關', text: '沿古碑道前往「碑林關」，挑戰道館④。', roles: ['rival2', 'boss4'], tiles: [['huanan', 13, 15], ['r5', 17, 15]] },
    { name: '第五道館．鐘塔台', text: '走考鐘坡（先找回遺失的准考證碎紙）前往「鐘塔台」，迎戰總複習大魔王！', roles: ['e1', 'e2', 'e3', 'moGuard', 'boss5'], tiles: [['beilin', 13, 16], ['r6', 17, 15]] },
    { name: '終章．堂堂正正走進考場', text: '准考證已經拼回來了！（可以繼續探索、收集武器，或回到主畫面。）', roles: [], tiles: [] },
  ];
  Object.defineProperty(S, 'chapterName', { get() { return !G || !G.flags.prologue ? '序幕．空白的早自習' : S.stages[Math.min(G.badges.length, 5)].name; }, configurable: true });
  /* 守護神器任務：小墨在鐘塔台道館門口的開場白 */
  S.moIntro = [
    '等一下！再上去就是最後一場了。',
    '那裡面有三個很強的學長姐，後面還有……墨塵最濃的那一個。',
    '你現在這樣上去，我怕你撐不住。',
    '……我跟你說一件事。文房四寶裡，有三隻器靈還醒著。',
    '筆、紙、墨。牠們不是道具，是願意陪人把話寫完的那種東西。',
    '牠們不會自己跑出來。要你先想清楚，才找得到。',
  ];
  S.moPick = [
    '小墨：「動筆啊……那你要找的是筆靈。牠最怕的就是有人一直不敢下筆。」',
    '小墨：「攤開來……嗯，那是紙靈。牠說過，藏著的心事最重。」',
    '小墨：「慢慢磨……那是墨靈。牠等一個沉得住氣的人很久了。」',
  ];
  S.roles = S.roles || {};
  Object.assign(S.roles, {
    gd_pen:   { kind: 'guardian', gq: 'g_pen',   name: '文心筆靈', look: { sprite: 'g_pen' } },
    gd_paper: { kind: 'guardian', gq: 'g_paper', name: '素心紙靈', look: { sprite: 'g_paper' } },
    gd_ink:   { kind: 'guardian', gq: 'g_ink',   name: '凝香墨靈', look: { sprite: 'g_ink' } },
  });
  Object.assign(S.gates, {
    moGuard: '（小墨擋在台階前：「先照我說的去一趟，回來我就讓開。」）' });
  Object.assign(S.mapNames, {
    c8: '晨讀教室', c1a: '注音坡道館', lib: '典籍港道館', yard: '花南街道館', hist: '碑林關道館', aud: '鐘塔台道館', inkpool: '硯海墨池',
    chendu: '晨讀村', r1: '晨讀田埂道', zhuyin: '注音坡', r2: '抄書石階', chaoshu: '抄書巷', r3: '運書河道',
    dianji: '典籍港', r4: '聲音鐘步道', tingyu: '聽雨亭', huanan: '花南街', r5: '古碑小徑', beilin: '碑林關',
    r6: '考鐘坡', moquan: '墨泉鄉', zhongta: '鐘塔台', home: '我的家',
    clinic_h: '保健室', store_h: '商店', clinic_c: '保健室', store_c: '商店', clinic_o: '保健室', store_o: '商店', forge: '鍛造工坊' });
  S.prologue = [
    '（……噹——噹——鐘聲響起。你從課桌上醒來。）',
    '剛才發下的「全國會考准考證」，竟然變成了一張空白的紙。',
    '紙上的墨水像有生命一樣剝落，化成黑色的「墨塵」，從窗戶飄散到整個校園……',
    '課本裡的字跡紛紛逃跑，走廊上的文具被墨塵附身，變成了在考卷堆裡巡邏的「武器妖」。',
    '（桌上的國文課本突然自己翻開了！）'];
  S.xiaomoIntro = [
    '呼——終於出來了！我是住在國文課本裡的墨靈，叫我「小墨」就好！',
    '大家對分數的過度焦慮，讓文字失去了原本的情感。准考證也跟著碎成五片，被五位館主搶走了！',
    '你必須用「理解」擊敗焦慮，才能拼回准考證！',
    '……糟糕，桌子底下的橡皮擦被墨塵附身了！拿起你的 2B 鉛筆，我把墨汁借給你！'];
  S.xiaomoAfter = [
    '做得好！橡皮擦妖掉下了碎片——看我的！',
    '打倒武器妖可以收集「碎片」，在選單的「鍛造」打造新武器；同名同階的武器還能升階喔！',
    '一年甲班的字音字形小老師被錯字怨念纏住了，第一片准考證碎片就在他那裡。出發吧！'];
  S.signs = Object.assign({}, S.signs, {
    sg0: '我的家',
    sg1: '商店',
    sg2: '保健室',
    sg3: '晨讀教室',
    sg4: '保健室',
    sg5: '道館',
    sg6: '道館',
    sg7: '二手書攤',
    sg8: '保健室',
    sg9: '鍛造工坊',
    sg10: '保健室',
    sg11: '商店',
    sg12: '道館',
    sg13: '道館',
    sg14: '保健室',
    sg15: '保健室',
    sg16: '商店',
    sg17: '道館',
    sg18: '道館',
    sg19: '保健室',
    sg20: '商店',
    sg21: '道館',
    sg22: '道館',
    sg23: '保健室',
    sg24: '商店',
    sg25: '道館',
    sg26: '道館',
    sg27: '保健室',
    sg28: '商店',
    sg29: '注音坡道館\n考：字音・字形',
    sg30: '典籍港道館\n考：成語',
    sg31: '花南街道館\n考：修辭・閱讀',
    sg32: '碑林關道館\n考：文言・常識',
    sg33: '鐘塔台道館\n考：全題型綜合',
    sign_chendu: '晨讀村\n↑ 晨讀田埂道　→ 注音坡',
    sign_zhuyin: '注音坡\n↑ 抄書石階　↓ 晨讀田埂道',
    sign_chaoshu: '抄書巷\n↑ 運書河道　↓ 抄書石階',
    sign_dianji: '典籍港\n↑ 聲音鐘步道　↓ 運書河道',
    sign_tingyu: '聽雨亭\n（休息站：茶屋可回復氣血）',
    sign_huanan: '花南街\n↑ 古碑小徑　↓ 聲音鐘步道',
    sign_beilin: '碑林關\n↑ 考鐘坡　↓ 古碑小徑',
    sign_moquan: '墨泉鄉\n（休息站：湯屋可回復氣血）',
    sign_zhongta: '鐘塔台\n會考的鐘聲從這裡敲響',
    sign_zhongta2: '（禮堂入口．集滿四片碎片者，方可應考）' });
  S.gates = Object.assign({}, S.gates, {
    need1: '道館守門人：「典籍港的道館只收有『第一片碎片』的人——先去注音坡的道館吧。」',
    need2: '道館守門人：「花南街的道館要兩片碎片才進得去。」',
    need3: '道館守門人：「碑林關的門需要三片碎片的光。」',
    need4: '道館守門人：「鐘塔台的大門寫著：『集滿四片碎片者，方可應考。』」',
    sideA: '（前面的柵欄被墨塵纏住了……先幫做分組報告的三位組員找回感受力吧。）',
    sideB: '（坡上的風太大，學弟妹哭著說准考證被吹碎了……先把三張碎紙找齊吧。）',
    stone: '（牆角的墨漬只是普通的污漬……好像還缺了什麼。）' });
  S.ending = [
    '總複習大魔王化成了無數張乾淨的白紙，輕輕飄落在禮堂裡。',
    '五片碎片發出溫暖的光芒，拼回了一張完整的准考證。',
    '小墨：「你做到了！不是靠死背，而是靠『理解』。文字終於找回了它的情感。」'];
  S.routeEnd = { a: '周以恆：「謝謝你當頭棒喝。從今天起，我要理解，不再只是背。」', b: '周以恆：「謝謝你懂我的壓力。原來古人和我們一樣，也會煩惱、也會努力。」' };
  S.finale = '鐘聲響起。你握緊准考證，堂堂正正地走進了考場。';
  S.guardians = { a: 'g_pen', b: 'g_paper' };
  S.routeNames = { a: '當頭棒喝', b: '同理之心' };

  Object.assign(S.roles, {
    xiaomo: { kind: 'guide', name: '小墨', look: { sprite: 'xiaomo' }, lines: [
      ['一年甲班就在走廊右邊那間教室！小老師會丟出「形近字」和「多音字」，仔細分辨喔。', '小老師被錯字纏住，屬性是「木」——你的 2B 鉛筆劍是「金」，金剋木！'],
      ['圖書館在校園左邊。成語圖書股長是「土」屬性，用成語字典（木）去剋他！', '成語不是背出來的，想想每個成語背後的故事。'],
      ['文學中庭在校園南邊。記得先點醒做分組報告的組員們，助教才會出來。', '文青助教是「火」屬性，修辭和閱讀（水）可以剋制他！'],
      ['校史室在校園右邊……我感覺到那個學霸的氣息。', '古典研究助教是「水」屬性，文言和國學常識（土）是他的剋星。'],
      ['大禮堂的菁英考生很強，記得多去錯題本複習、把武器升階！', '大魔王會用所有題型攻擊，還會考「段落排序」。守護神器和文氣必殺會是你的好幫手！'],
      ['准考證拼回來了！謝謝你，文字們又能好好說話了。']] },
    c1aTip: { name: '一年級學妹', look: stu('#3a2a20', '#3a58a0', { gender: 'f', bag: '#f08ab0' }), lines: ['小老師最近每天都在罰寫錯字，寫到眼睛都黑掉了，好可怕……'] },
    tipA: { name: '值日生', look: stu('#1a1a20', '#3a58a0'), lines: ['保健室在校園左下角，福利社在右下角。受傷了記得去休息！'] },
    tipB: { name: '美術班同學', look: stu('#c86a3a', '#3a58a0', { gender: 'f', bag: '#e86ab0' }), lines: ['走廊的考卷堆裡有好多文具妖。打倒牠們收集碎片，就能打造新武器喔！'] },
    tipC: { name: '園藝社社員', look: stu('#4a3020', '#2e6a4a', { gender: 'f' }), lines: ['中庭在校園南邊。最近大家在做觀察生活的分組報告，可是好像吵起來了……'] },
    dictA: { kind: 'trainer', name: '被聽寫逼瘋的同學', look: stu('#3a2a20', '#3a58a0', { bag: '#3a8a48' }), reward: 120,
      foe: { lv: 4, hpMul: 1.6, el: '木', cats: ['字音', '字形'], moves: [['聽寫轟炸', ['字形'], 40], ['注音連發', ['字音'], 40]] },
      intro: '聽寫……聽寫……每個字都長得好像……你也來寫寫看！', win: '咦？我剛剛怎麼了……謝謝你讓我清醒！', after: '形近字看部首，多音字看詞語，就不容易錯了。' },
    dictB: { kind: 'trainer', name: '被注釋淹沒的同學', look: stu('#1a1a20', '#3a58a0', { gender: 'f', bag: '#8a58c8' }), reward: 150,
      foe: { lv: 5, hpMul: 1.7, el: '水', cats: ['字音', '字形', '詞義'], moves: [['注釋漩渦', ['詞義'], 45], ['錯字泥沼', ['字形'], 45]] },
      intro: '注釋……我要把全部注釋背下來……不准打擾我！', win: '……原來注釋是幫助理解的，不是用來死背的。', after: '走廊盡頭有個寶箱，好像有人掉了國文課本在裡面。' },
    boss1: { kind: 'gym', name: '字音字形小老師', badge: '准考證碎片（一）', badgeColor: '#d07a1a', reward: 500, rewardWeapon: 'tome', rewardRarity: 1, hpMod: { flag: 'bbAll', mul: 0.8 },
      look: stu('#181820', '#c83838', { glasses: 1, bag: '#c83838' }),
      foe: { lv: 7, hpMul: 2.7, el: '木', cats: ['字音', '字形'], moves: [['形近字暗器', ['字形'], 50], ['多音字暗器', ['字音'], 50], ['錯字怨念', ['字音', '字形'], 62]] },
      intro: '錯……錯……全都是錯字！一個錯字扣一分……我不要再被扣分了！\n\n（小老師的眼睛被黑墨占滿，朝你丟出了形近字與多音字的暗器！）',
      win: '……我的眼睛，好像看清楚了。',
      afterWin: ['謝謝你。我一直怕寫錯字被扣分，結果越怕越錯……原來要先弄懂字的意思啊。', '這片碎片還給你。還有——你看窗外！圖書館那邊的墨塵更濃了！'],
      after: '形近字要從部首判斷意思，例如「睫」有目字旁，所以是「迫在眉睫」。' },
    rival1: { kind: 'rival', name: '學霸 周以恆', look: stu('#101018', '#303048', { glasses: 1, bag: '#303038' }), reward: 300,
      foe: { lv: 9, hpMul: 2.3, el: '土', cats: ['成語', '詞義'], moves: [['題庫砸擊', ['成語'], 48], ['死背連擊', ['詞義'], 52]] },
      intro: '你還在一隻一隻打怪練等？真沒效率。\n\n只要把成語辭典整本背下來，根本不需要理解什麼典故！讓你見識一下什麼叫實力！',
      win: '……怎麼可能？我明明全都背起來了……', afterWin: ['哼，這次只是運氣好！', '（周以恆不甘心地跑進了圖書館深處。）'], after: '……' },
    boss2: { kind: 'gym', name: '成語圖書股長', badge: '准考證碎片（二）', badgeColor: '#3e9830', reward: 700, rewardWeapon: 'fan', rewardRarity: 1, needDefeated: ['dianji:rival1'],
      gateText: '（成語辭典在空中亂飛，股長被書堆包圍，你根本靠近不了……）',
      look: stu('#2a2a2a', '#3e9830', { glasses: 1, gender: 'f', outfit: 'skirt', pants: '#2e5a3a' }),
      foe: { lv: 11, hpMul: 3.0, el: '土', cats: ['成語', '常識'], moves: [['成語飛書', ['成語'], 52], ['六書迷陣', ['常識'], 52], ['典故洪流', ['成語', '常識'], 65]] },
      intro: '安靜！圖書館內禁止喧嘩！\n\n想拿回碎片？先通過成語填空與六書判斷的考驗！',
      win: '……原來我也只是把成語「收藏」起來，卻忘了讀懂它們。',
      afterWin: ['成語不是用背的，每個成語背後都有一個故事啊。', '對了，中庭好像發生了很嚴重的爭執，你快去看看！'],
      after: '「象形、指事、會意、形聲、轉注、假借」，這就是六書。' },
    m1: { kind: 'trainer', name: '報告組員 阿凱', look: stu('#3a2a20', '#e07a30', { bag: '#e07a30' }), reward: 200,
      foe: { lv: 11, hpMul: 1.7, el: '火', cats: ['閱讀', '修辭'], moves: [['噪音攻擊', ['閱讀'], 48], ['冷漠一瞥', ['修辭'], 48]] },
      intro: '賣芭樂的老阿伯叫賣聲？那根本只是噪音啦！哪裡像時鐘了？', win: '……仔細聽，阿伯每天都在同一個時間經過，那聲音真的在告訴我們「現在幾點」耶。', after: '我要重寫報告！' },
    m2: { kind: 'trainer', name: '報告組員 小婷', look: stu('#201818', '#e07a30', { gender: 'f', outfit: 'skirt', pants: '#303048' }), reward: 200,
      foe: { lv: 11, hpMul: 1.7, el: '火', cats: ['閱讀', '修辭'], moves: [['字數灌水', ['閱讀'], 48], ['空洞修辭', ['修辭'], 48]] },
      intro: '什麼生活的美感？報告只要寫滿字數就好了！', win: '原來作者是在說：只要用心聽，平凡的聲音也有溫度。', after: '謝謝你，我終於知道要寫什麼了。' },
    m3: { kind: 'trainer', name: '報告組員 阿翔', look: stu('#5a3a24', '#e07a30', { bag: '#303038' }), reward: 200,
      foe: { lv: 12, hpMul: 1.8, el: '火', cats: ['閱讀', '修辭'], moves: [['無聊結界', ['閱讀'], 50], ['敷衍一擊', ['修辭'], 50]] },
      intro: '這篇課文好無聊……聲音就是聲音，有什麼好觀察的？', win: '……下次放學，我也要仔細聽聽巷口的聲音。', after: '助教在涼亭那邊，你去找他吧！' },
    boss3: { kind: 'gym', name: '現代文青助教', badge: '准考證碎片（三）', badgeColor: '#2a78c8', reward: 900, rewardWeapon: 'seal', rewardRarity: 1, needDefeated: ['r4:m1', 'r4:m2', 'r4:m3'], atkMod: { flag: 'flAll', mul: 0.8 },
      gateText: '助教：「你的組員都還不懂得『感受』，就想挑戰我？先去點醒他們吧。」',
      look: stu('#3a2a24', '#6a5a4a', { hat: '#8a4a3a', glasses: 1, cloth: '#e8dcc0' }),
      foe: { lv: 14, hpMul: 2.7, el: '火', cats: ['閱讀', '修辭'], moves: [['艱澀長文', ['閱讀'], 55], ['譬喻風暴', ['修辭'], 55], ['意境結界', ['閱讀', '修辭'], 68]] },
      intro: '現代人只會滑手機，早就失去感受文字的能力了。\n\n不信？讓我用白話文閱讀測驗和修辭法證明給你看。',
      win: '……我錯了。能感受文字的人，一直都在。',
      afterWin: ['（同學們順利完成了分組報告。）', '謝謝你。對了……校史室那邊，有個學生對著滿牆的古文在崩潰，你去看看吧。'],
      after: '修辭不是背名稱，而是去感受作者想傳達的畫面與情感。' },
    rival2: { kind: 'rival', name: '學霸 周以恆', look: stu('#101018', '#303048', { glasses: 1, bag: '#303038' }), reward: 500,
      foe: { lv: 13, hpMul: 2.6, el: '水', cats: ['文言'], moves: [['翻譯狂背', ['文言'], 55], ['崩潰吶喊', ['文言'], 60]] },
      intro: '上次模擬考的文言文，我竟然全錯……\n\n古文根本不實用！我只要把白話翻譯全部背下來應付考試就好！不要擋我！',
      win: '……為什麼……背了那麼多，還是不懂……',
      choice: { q: '周以恆抱著頭大喊：「古文根本不實用！我只要把翻譯全背下來就好！」\n\n你要怎麼回答？',
        opts: ['「不要逃避了！去理解文字背後的邏輯！」', '「我懂很難，但古人的煩惱跟我們很像。」'],
        replies: ['……當頭棒喝。你說得對，我一直在逃避。文言文是古人智慧的濃縮……', '……古人也會煩惱嗎？好，我試著慢慢看，不再只是背。'] },
      afterA: '我要重新讀懂每一句古文。去吧，古典研究助教就在裡面！', afterB: '謝謝你懂我的壓力。去吧，古典研究助教就在裡面！', after: '……' },
    boss4: { kind: 'gym', name: '古典研究助教', badge: '准考證碎片（四）', badgeColor: '#9a6a3a', reward: 1100, rewardWeapon: 'classic', rewardRarity: 2, needDefeated: ['r5:rival2'],
      gateText: '（一股古人的威壓從檔案室深處傳來，你的腳步被擋住了……）',
      look: { hair: '#505058', cloth: '#6a5a4a', cloth2: '#c8a040', robe: 1, glasses: 1, cap: '#303030', beard: 1 },
      foe: { lv: 17, hpMul: 3.2, el: '水', cats: ['文言', '常識'], moves: [['之乎者也', ['文言'], 58], ['國學威壓', ['常識'], 58], ['文言題組', ['文言', '常識'], 72]] },
      intro: '汝等後生，可知古人之言？\n\n今日便以長篇文言題組與國學常識，試汝之學！冷靜析其上下文意，方能傷吾分毫。',
      win: '……善。能析文理，不以死背為能，可教也。',
      afterWin: ['（周以恆走了過來，眼神清澈了許多。）', '准考證只剩最後一片了……這時，大禮堂傳來了沉重的鐘聲！'],
      after: '讀文言文，先找出主詞與動詞，再推敲字義與上下文。' },
    /* ---- 各道館的館內對手（打贏館主前的練習關卡） ---- */
    gy1a: { kind: 'trainer', name: '注音小老師 林昀', look: stu('#2a2a2a', '#e8a030'), reward: 150,
      foe: { lv: 5, hpMul: 1.2, el: '金', cats: ['字音'], moves: [['ㄅㄆㄇ連發', ['字音'], 44], ['破音字陷阱', ['字音'], 46]] },
      intro: '要挑戰小老師？先過我這關！', win: '唸得比我還準……', after: '小老師就在講台那邊。' },
    gy1b: { kind: 'trainer', name: '值日生 周昕', look: stu('#4a2a1a', '#e8a030', { gender: 'f', outfit: 'skirt', pants: '#303048' }), reward: 160,
      foe: { lv: 6, hpMul: 1.2, el: '土', cats: ['字形'], moves: [['錯字糾察', ['字形'], 46], ['部首拆解', ['字形'], 46]] },
      intro: '黑板我剛擦乾淨，別弄髒了喔！', win: '好啦，讓你過。', after: '加油，別寫錯字。' },
    gy2a: { kind: 'trainer', name: '圖書小志工 何芷', look: stu('#3a2a20', '#3a6a9a', { gender: 'f' }), reward: 220,
      foe: { lv: 9, hpMul: 1.4, el: '水', cats: ['成語'], moves: [['成語接龍', ['成語'], 50], ['典故考據', ['成語'], 50]] },
      intro: '書架上的成語辭典自己飛起來了……小心！', win: '看來你真的讀過。', after: '往裡面走，股長在最深處。' },
    gy2b: { kind: 'trainer', name: '搬書工讀生 陳彥', look: stu('#1a1a20', '#3a6a9a'), reward: 230,
      foe: { lv: 10, hpMul: 1.4, el: '木', cats: ['詞義'], moves: [['疊字攻勢', ['詞義'], 52], ['近義辨析', ['詞義'], 52]] },
      intro: '箱子後面有路，不過要先過我。', win: '……你比我會找路。', after: '別踩到我的箱子。' },
    gy3a: { kind: 'trainer', name: '園藝社 蘇沐', look: stu('#5a3a24', '#d8629a', { gender: 'f', outfit: 'skirt', pants: '#8e5878' }), reward: 280,
      foe: { lv: 13, hpMul: 1.5, el: '木', cats: ['修辭'], moves: [['譬喻花雨', ['修辭'], 54], ['擬人藤蔓', ['修辭'], 54]] },
      intro: '這些花會照你寫的句子開喔。', win: '你的句子很漂亮。', after: '紅毯盡頭就是助教了。' },
    gy3b: { kind: 'trainer', name: '文藝社長 邱恆', look: stu('#2a2a2a', '#d8629a'), reward: 290,
      foe: { lv: 14, hpMul: 1.5, el: '火', cats: ['現代文', '閱讀'], moves: [['散文長句', ['閱讀'], 56], ['新詩斷句', ['修辭'], 56]] },
      intro: '寫得漂亮沒用，要讓人看懂。', win: '……我好像懂了。', after: '去吧。' },
    gy4a: { kind: 'trainer', name: '拓碑社 高硯', look: stu('#3a3038', '#8a4a3a'), reward: 340,
      foe: { lv: 16, hpMul: 1.6, el: '土', cats: ['文言'], moves: [['碑文壓境', ['文言'], 58], ['虛字辨義', ['文言'], 58]] },
      intro: '碑上的字，你認得幾個？', win: '……原來還有人讀得懂。', after: '再往裡走。' },
    gy4b: { kind: 'trainer', name: '古文社 溫亦', look: stu('#4a2a1a', '#8a4a3a', { gender: 'f', glasses: 1 }), reward: 350,
      foe: { lv: 17, hpMul: 1.6, el: '金', cats: ['詩詞'], moves: [['律詩對仗', ['詩詞'], 58], ['平仄壓制', ['詩詞'], 58]] },
      intro: '對不出下聯，就別想過去。', win: '對得不錯。', after: '助教在碑牆後面。' },
    gy5a: { kind: 'trainer', name: '考前衝刺班 江嶼', look: stu('#1a1a20', '#c8a040'), reward: 380,
      foe: { lv: 18, hpMul: 1.7, el: '火', cats: ['常識', '閱讀'], moves: [['考古題海', ['閱讀'], 60], ['冷知識突襲', ['常識'], 60]] },
      intro: '離會考剩幾天了，你知道嗎？', win: '……知道日期也沒用，要會寫才行。', after: '上去吧，他們在等你。' },
    gy5b: { kind: 'trainer', name: '自習室常客 鍾瑀', look: stu('#3a2a20', '#c8a040', { gender: 'f' }), reward: 390,
      foe: { lv: 19, hpMul: 1.7, el: '水', cats: ['修辭', '字形'], moves: [['筆記轟炸', ['字形'], 60], ['重點畫線', ['修辭'], 60]] },
      intro: '我的筆記本比你的課本厚。', win: '厚不代表懂……我懂了。', after: '講台上那三個，很強。' },
    e1: { kind: 'trainer', name: '模考榜首 方宥寧', look: stu('#1a1a20', '#c8a040', { glasses: 1 }), reward: 400,
      foe: { lv: 19, hpMul: 2.8, el: '金', cats: ['字形', '成語', '詩詞'], moves: [['滿分筆觸', ['字形'], 55], ['成語速答', ['成語'], 55]] },
      intro: '會考只看分數。你這種靠理解的人，走不上講台的！', win: '……原來分數之外，還有這麼多東西。', after: '加油，別輸給大魔王。' },
    e2: { kind: 'trainer', name: '筆記女王 許安琪', look: stu('#3a2a20', '#c8a040', { gender: 'f', outfit: 'skirt', pants: '#303048' }), reward: 400,
      foe: { lv: 20, hpMul: 2.8, el: '木', cats: ['修辭', '閱讀', '文言'], moves: [['高速閱讀', ['閱讀'], 58], ['古文壓迫', ['文言'], 58]] },
      intro: '我每天寫十份模擬考。你呢？', win: '……我好像一直在寫題目，卻忘了讀文章。', after: '去吧，講台就在前面。' },
    e3: { kind: 'trainer', name: '速讀狂人 陳柏叡', look: stu('#5a3a24', '#c8a040', { bag: '#303038' }), reward: 400,
      foe: { lv: 21, hpMul: 2.7, el: '火', cats: ['常識', '詩詞', '詞義'], moves: [['常識轟炸', ['常識'], 58], ['詩詞焰', ['詩詞'], 58]] },
      intro: '最後一道防線！讓我看看你的錯題本複習得怎麼樣！', win: '……你真的把錯題都弄懂了。', after: '大魔王就在講台上。' },
    moGuard: { kind: 'guardian', name: '小墨', look: { sprite: 'xiaomo' }, needDefeated: ['aud:e1', 'aud:e2', 'aud:e3'],
      lines: ['{name}，等一下。', '講台上的那個東西，是把全校的焦慮揉成一團做出來的……光靠文具，可能撐不住。',
        '不過，只要你心裡還相信文字，文房四寶就會來幫你。我問你一句話就好——'],
      choice: { q: '小墨看著你：「對你來說，讀國文到底是為了什麼？」',
        opts: ['為了看懂別人想說的話', '為了把自己想說的話說清楚'],
        replies: ['……嗯，那是「讀」的力量。', '……嗯，那是「寫」的力量。'] },
      afterGive: '牠會陪你一起上場的。去吧，別怕那團墨。',
      after: '準備好了就上講台吧！' },
    boss5: { kind: 'gym', name: '總複習大魔王', badge: '准考證碎片（五）', badgeColor: '#b8322a', reward: 3000, final: true, leaves: true, potions: 2, needDefeated: ['aud:e1', 'aud:e2', 'aud:e3', 'aud:moGuard'], wenqiFlags: ['ad1', 'ad2', 'ad3'],
      gateText: '（小墨還有話要說……先聽他說完再上台吧！）',
      look: { sprite: 'boss' },
      entryLines: ['（一團黑影砸穿天花板，落在紅毯正中央。粉筆灰像雪一樣慢慢飄下來。）',
        '……吵死了。',
        '你們三個沒用的東西，連一個學生都攔不住。',
        '我是全校累積下來的「來不及」。每一次熬夜、每一張沒訂正的考卷，都是我的一部分。',
        '（牠把答案卡狀的胸口翻開，裡面全是紅色的叉。）',
        '來吧。讓我看看你寫得出什麼。'],
      foe: { lv: 24, hpMul: 4.9, el: 'none', cats: ['閱讀', '文言', '詩詞', '成語', '修辭', '字形', '字音', '詞義', '常識'], moves: [['全題型轟炸', ['閱讀', '文言'], 62], ['模擬考卷海', ['成語', '詩詞'], 62], ['空白作文紙', ['修辭', '字形'], 62], ['段落錯亂', ['閱讀'], 72, 'order']] },
      intro: '空白的作文紙、寫不完的模擬考卷……全部都是你們的焦慮！\n\n在我面前，你們只能死背、只能害怕！',
      win: '……為什麼……你……不怕我……？', afterWin: [], after: '……' },

    /* ---------- 通關後（後日談） ---------- */
    postMo: { kind: 'guide', name: '小墨',
      look: { sprite: 'xiaomo' },
      lines: [[
        '准考證拼回來了，校園裡的墨塵也散了……但我還在喔。',
        '因為只要有人願意「理解」文字，我就會一直住在課本裡。',
        '考試不是終點，讀懂一句話、被一首詩打動，才是你真正帶得走的東西。'],
      ['對了，講台上的墨痕還沒完全散去——如果你想再挑戰一次「總複習大魔王」的影子，隨時可以來找我。',
        '還有，如果你進了二週目，記得去校園牆角那道墨漬看看。文房四寶之首就在底下，牠只認真心讀書的人。']] },
    postBoss: { kind: 'rematch', name: '大魔王的殘影', look: { sprite: 'boss' },
      lines: ['講台上還殘留著一團墨影，不斷重播著考前的焦慮……', '（它似乎比上次更強了。）'],
      ask: '要挑戰「總複習大魔王．殘影」嗎？（等級會隨著你成長）',
      no: '……那就等你準備好再來吧。',
      reward: 1200, win: '墨影散去，留下了一疊閃著光的碎片。',
      foe: { lv: 26, hpMul: 5.2, el: 'none', cats: ['閱讀', '文言', '詩詞', '成語', '修辭', '字形', '字音', '詞義', '常識'],
        moves: [['全題型轟炸', ['閱讀', '文言'], 64], ['模擬考卷海', ['成語', '詩詞'], 64], ['空白作文紙', ['修辭', '字形'], 64], ['段落錯亂', ['閱讀'], 74, 'order']] },
      potions: 2, prize: { money: 1200, frags: 3, items: { heal2: 2, cure: 1 } } },
    postRival: { kind: 'rematch', name: '學霸 周以恆', look: stu('#101018', '#303048', { glasses: 1, bag: '#303038' }),
      lines: ['{name}！聽說你把准考證拼回來了。', '……我不服氣。不對，是「我想再學一次」——這次我不死背了。'],
      ask: '要和周以恆再對練一場嗎？（可以賺經驗值與積分）',
      no: '好，那我先去讀書了。想練習的時候再來找我！',
      reward: 600, win: '……又輸了。不過這次我懂了為什麼。',
      foe: { lv: 22, hpMul: 2.4, el: '水', cats: ['文言', '成語', '閱讀'], moves: [['題海戰術', ['成語'], 58], ['翻譯快打', ['文言'], 58], ['速讀', ['閱讀'], 62]] },
      potions: 2, prize: { money: 600, frags: 1, items: { heal: 2 } } },
  });
  /* 新世界的城鎮與路線人物 */
  const stu2 = (hair, c2, extra) => Object.assign({ hair, cloth: '#f8f8f8', cloth2: c2, style: 'school' }, extra || {});
  Object.assign(S.roles, {
    busStop: { kind: 'bus', name: '公車站牌', look: { hair: '#4a4a52', cloth: '#3a68b8', hat: '#2a4a88' },
      lines: ['要搭車去別的城鎮嗎？（只能去已經到過的地方）'] },
    tipHome: { name: '村口的阿婆', look: { hair: '#b0b0b0', cloth: '#c8a060', gender: 'f' },
      lines: ['以前每天早上，全村會一起朗讀喔。', '那天早上聲音突然斷掉……你也是那時候醒來的吧？'] },
    townTip1: { name: '注音坡的學弟', look: stu2('#3a2a20', '#e8a030'),
      lines: ['壁畫上的注音都被墨塵弄花了，大家開始念錯字。', '道館在坡下的大校舍，門口有守門人喔。'] },
    townTip2: { name: '抄書巷的老師傅', look: { hair: '#909090', cloth: '#8a5a3a' },
      lines: ['這條巷子以前家家戶戶都在抄書。', '碎片合成、武器升階，交給我準沒錯——就在旁邊的鍛造工坊。'] },
    townTip3: { name: '碼頭工人', look: { hair: '#2a2a2a', cloth: '#4a6a8a' },
      lines: ['書都是從這個港口上岸的，連成語典故都是「隨船來的」。', '圖書股長就在倉庫改成的道館裡。'] },
    townTip4: { name: '聽雨亭的旅人', look: { hair: '#5a3a2a', cloth: '#6a8a6a' },
      lines: ['屋簷把雨滴敲成一段一段的，大家叫它「聲音鐘」。', '累了就去茶屋休息，泡杯茶氣血就全滿了。'] },
    townTip5: { name: '花店老闆娘', look: { hair: '#6a3a2a', cloth: '#e86ab0', gender: 'f' },
      lines: ['招牌要寫得讓人一眼看懂，又願意多看一眼——這就是修辭啊。'] },
    townTip6: { name: '碑林的老書院生', look: { hair: '#808080', cloth: '#8a7a5a' },
      lines: ['每塊碑都是一段古文。看不懂碑文的人，連城門都過不去。'] },
    springTip: { name: '泉邊的老人', look: { hair: '#a0a0a0', cloth: '#4a5a72' },
      lines: ['這裡的泉水帶著墨色，老一輩說底下通著「硯海」。', '牆角那道墨漬……偶爾會自己裂開一條縫，但不是誰都能進去。'] },
    ngHint: { kind: 'guide', name: '小墨', look: { sprite: 'xiaomo' },
      lines: [['你也覺得奇怪吧？墨塵怎麼又回來了。',
        '我跟你說一件事：世界上的器靈不只三隻。筆、紙、墨之外，還有一隻「四寶之首」。',
        '要喚醒牠，你得先把筆、紙、墨三隻器靈都收齊，而且**三隻都要帶在身上**，再到墨泉鄉的泉眼前——牠才會回應你。']] },
    gymTip1: { name: '道館守門人', look: { hair: '#2a2a2a', cloth: '#c83838', hat: '#a02828' },
      lines: ['這裡是注音坡道館，考「字音」和「字形」。準備好就進去吧！'] },
    gymTip2: { name: '道館守門人', look: { hair: '#2a2a2a', cloth: '#c83838', hat: '#a02828' },
      lines: ['典籍港道館考「成語」。要有第一片碎片才進得去喔。'] },
    gymTip3: { name: '道館守門人', look: { hair: '#2a2a2a', cloth: '#c83838', hat: '#a02828' },
      lines: ['花南街道館考「修辭」與「閱讀」。兩片碎片才能進去。'] },
    gymTip4: { name: '道館守門人', look: { hair: '#2a2a2a', cloth: '#c83838', hat: '#a02828' },
      lines: ['碑林關道館考「文言」與「常識」。三片碎片才能進去。'] },
    gymTip5: { name: '道館守門人', look: { hair: '#2a2a2a', cloth: '#c83838', hat: '#a02828' },
      lines: ['鐘塔台道館……裡面的東西已經不是人了。四片碎片才能進去。'] },
    sparring: { kind: 'rematch', name: '詩社學姊', look: stu2('#201818', '#8a58c8', { gender: 'f' }),
      lines: ['要對練嗎？我不收錢，只收你認真的態度。'], ask: '要和詩社學姊對練一場嗎？（可重複挑戰）', no: '好，想練的時候再來。',
      reward: 260, win: '不錯嘛！比上次更穩了。',
      foe: { lv: 10, hpMul: 1.6, el: '水', cats: ['修辭', '詩詞'], moves: [['吟詠', ['詩詞'], 50], ['譬喻', ['修辭'], 50]] },
      potions: 1, prize: { money: 260, items: { heal: 1 } } },
    sideAGiver: { kind: 'quest2', name: '報告組長 小婕', look: stu2('#2a1a14', '#3a8a58', { gender: 'f' }),
      offer: '我們要錄「生活中的聲音」做分組報告，可是三個組員被墨塵纏住，全散在步道上了……可以幫我叫醒他們嗎？',
      progress: '還有人沒醒過來……他們就在步道的草叢附近。',
      done: '太好了，大家都醒了！這個給你，謝謝你！',
      after: '報告順利完成了，謝謝你！', need: ['r4:m1', 'r4:m2', 'r4:m3'],
      prize: { money: 400, items: { heal2: 2, ward: 1 } } },
    sideBGiver: { kind: 'quest2', name: '哭著的學弟', look: stu2('#1a1a24', '#4a78c8'),
      offer: '我的准考證被風吹碎了……三張碎紙全被吹到坡上去了，我不敢一個人去撿……',
      progress: '還差幾張……碎紙好像卡在石碑和草叢裡。',
      done: '謝謝你！我一定會好好考的！',
      after: '謝謝你幫我撿回准考證！', needFlag: 'sideB',
      prize: { money: 500, items: { heal2: 2, cure: 2 } } },
    forgeTip: { name: '工坊學徒', look: { hair: '#3a2a20', cloth: '#8a5a3a' },
      lines: ['師傅在裡面顧爐子，碎片合成跟武器升階都找他。', '對了，武器太多帶不動的話，選單裡有「電腦」可以寄放喔。'] },
    roamHint2: { kind: 'roam', name: '路過的登山客', look: { hair: '#4a3a2a', cloth: '#6a8a5a', hat: '#8a6a3a' },
      idle: ['山路小心，草叢裡有武器妖。', '走累了就到前面的城鎮休息吧。'],
      found: '剛才有個會發光的東西往「{map}」的方向去了！', none: '最近山上安靜多了。' },
    roamHint: { kind: 'roam', name: '街角的小孩', look: { hair: '#2a2a2a', cloth: '#e8a030' },
      idle: ['最近街上沒什麼特別的……', '聽說有會發光的東西在外面跑，但我沒看過。'],
      found: '我剛剛在「{map}」那邊看到會發光的東西！一下子就不見了……',
      none: '聽說有人集滿了傳說中的器靈耶！' },
    sparring2: { kind: 'rematch', name: '茶屋的老闆', look: { hair: '#5a4a3a', cloth: '#6a8a6a' },
      lines: ['泡茶要等，讀書也是。要不要陪我打一場？'], ask: '要和茶屋老闆對練一場嗎？（可重複挑戰）', no: '好，茶隨時幫你留著。',
      reward: 320, win: '嗯，你的沉穩比上次好多了。',
      foe: { lv: 12, hpMul: 1.7, el: '木', cats: ['詞義', '文言'], moves: [['慢火細讀', ['文言'], 52], ['字字回甘', ['詞義'], 52]] },
      potions: 1, prize: { money: 320, items: { heal2: 1 } } },
    /* ---- 城鎮居民：話家常、送禮物、答題送道具 ---- */
    t_cd_a: { kind: 'gift', name: '晨讀村的阿嬤', look: { hair: '#d8d8d8', cloth: '#a8845c', gender: 'f' },
      lines: ['你是要去注音坡的那個孩子吧？', '田埂路早上會有露水，滑得很。這個給你墊墊肚子。'],
      items: { heal: 2 }, after: '路上小心啊。' },
    t_cd_b: { kind: 'quiz', name: '曬書的伯伯', look: { hair: '#6a5a4a', cloth: '#7a8a6a' },
      lines: ['書曬過太陽才不會長蟲。', '你既然要去考試，我考你一題，答對了這本借你。'],
      ask: '曬書伯伯要考你一題字音，要試試看嗎？', cat: '字音',
      items: { hint: 2 }, money: 120, win: '好！讀過書的孩子就是不一樣。', after: '書我幫你留著。' },
    t_zy_a: { kind: 'gift', name: '盪鞦韆的小朋友', look: { hair: '#3a2a20', cloth: '#6aa8d8' },
      lines: ['哥哥你要去挑戰小老師嗎？', '那個⋯⋯這個糖給你，你會用得到！'],
      items: { heal: 1, wenqi: 1 }, after: '加油喔！' },
    t_zy_b: { kind: 'quiz', name: '掃地的工友', look: { hair: '#5a5a5a', cloth: '#8a8a7a' },
      lines: ['牆上那些被墨塗掉的注音，掃都掃不掉。', '你要是唸得出來，我這裡有東西給你。'],
      ask: '工友要考你一題字形，要試試看嗎？', cat: '字形',
      items: { ward: 1 }, money: 150, win: '唸得真準！牆上的墨好像淡了一點。', after: '再多唸幾遍給牆聽吧。' },
    t_cs_a: { kind: 'gift', name: '抄書巷的學徒', look: { hair: '#2a2a2a', cloth: '#a8463c' },
      lines: ['我抄了一整天，手都麻了。', '這支筆給你，我還有。'],
      items: { hint: 1, heal: 1 }, after: '抄書是笨功夫，但很有用。' },
    t_cs_b: { kind: 'quiz', name: '紙鋪老闆娘', look: { hair: '#4a2a1a', cloth: '#c8785a', gender: 'f' },
      lines: ['這條巷子最不缺的就是紙。', '答對我一題，我送你一些好東西。'],
      ask: '老闆娘要考你一題詞義，要試試看嗎？', cat: '詞義',
      items: { heal2: 1 }, money: 180, win: '讀書人！這些拿去。', after: '紙要挑好的，字才寫得穩。' },
    t_dj_a: { kind: 'gift', name: '碼頭搬運工', look: { hair: '#1a1a20', cloth: '#4a6a8a' },
      lines: ['這些書箱重死了，你幫我扶一下⋯⋯謝啦！', '這個給你，路上補補。'],
      items: { heal2: 1 }, after: '書比石頭還重，真的。' },
    t_dj_b: { kind: 'quiz', name: '船上的先生', look: { hair: '#3a3038', cloth: '#5a5a7a', glasses: 1 },
      lines: ['這船載的都是成語辭典，一本比一本厚。', '你要是答得出來，我送你一本裡面的東西。'],
      ask: '船上的先生要考你一題成語，要試試看嗎？', cat: '成語',
      items: { ward: 1, hint: 1 }, money: 200, win: '好，果然有讀。', after: '船要開了，再見。' },
    t_ty_a: { kind: 'gift', name: '躲雨的旅人', look: { hair: '#5a3a2a', cloth: '#6a8a6a' },
      lines: ['雨太大了，我躲一下。', '你也淋濕了吧？這個熱的給你。'],
      items: { heal2: 2 }, after: '等雨小一點我就走了。' },
    t_hn_a: { kind: 'gift', name: '賣花的姑娘', look: { hair: '#6a3a2a', cloth: '#e86ab0', gender: 'f' },
      lines: ['這朵花開得像剛吵完架的人，你不覺得嗎？', '送你一朵，帶著走運氣會好。'],
      items: { dodgeup: 1 }, after: '花要多看，句子才寫得出來。' },
    t_hn_b: { kind: 'quiz', name: '寫招牌的師傅', look: { hair: '#2a2a2a', cloth: '#8a6a4a' },
      lines: ['招牌要寫得讓人一眼看懂，又願意多看一眼。', '我考你一題，答對了這塊小牌子送你。'],
      ask: '師傅要考你一題修辭，要試試看嗎？', cat: '修辭',
      items: { atkup: 1 }, money: 220, win: '有慧根！這塊給你。', after: '字要寫得讓人想停下來看。' },
    t_bl_a: { kind: 'gift', name: '拓碑的老先生', look: { hair: '#e8e8e8', cloth: '#8a7a5a', beard: 1 },
      lines: ['碑上的字，一千年了還在。', '你帶著這個，讀古文的時候會順一點。'],
      items: { wenqi: 2 }, after: '慢慢讀，碑不會跑。' },
    t_bl_b: { kind: 'quiz', name: '守門的士兵', look: { hair: '#2a2a2a', cloth: '#7a7a8a' },
      lines: ['城門裡面的碑林，沒讀過書的進去會迷路。', '我考你一題，過了我就放心。'],
      ask: '士兵要考你一題文言，要試試看嗎？', cat: '文言',
      items: { defup: 1 }, money: 250, win: '通過。進去吧。', after: '碑林裡小心腳下。' },
    t_mq_a: { kind: 'gift', name: '泡湯的老翁', look: { hair: '#d8d8d8', cloth: '#6a7a8a', beard: 1 },
      lines: ['墨泉的水泡久了，身上會有墨香。', '這罐給你，比泡湯快。'],
      items: { cure: 2 }, after: '泉水底下有東西，別太靠近。' },
    t_mq_b: { kind: 'quiz', name: '磨墨的孩子', look: { hair: '#3a2a20', cloth: '#5a6a7a' },
      lines: ['磨墨要一直磨一直磨，不能停。', '你答對我一題，我把磨好的分你一些。'],
      ask: '磨墨的孩子要考你一題詩詞，要試試看嗎？', cat: '詩詞',
      items: { wenqi: 2 }, money: 200, win: '哇，你很厲害耶！', after: '我要繼續磨了。' },
    t_zt_a: { kind: 'gift', name: '鐘塔台的清潔員', look: { hair: '#5a5a5a', cloth: '#8a8a7a' },
      lines: ['紅毯上的墨塵掃不完，掃一次來一次。', '你要上去的話，這個帶著。'],
      items: { heal2: 2, cure: 1 }, after: '上面那個⋯⋯很不好惹。' },
    t_zt_b: { kind: 'quiz', name: '看榜的學生', look: { hair: '#1a1a20', cloth: '#c8a040' },
      lines: ['我每天都來看榜，但榜上從來沒有我的名字。', '你答對一題，我把我的護身符給你——我用不到了。'],
      ask: '看榜的學生要考你一題閱讀，要試試看嗎？', cat: '閱讀',
      items: { ward: 2 }, money: 300, win: '⋯⋯你真的讀懂了。那就交給你了。', after: '替我進去看看。' },
    t_r2a: { kind: 'trainer', name: '抄書學徒 阿丹', look: stu2('#3a2a20', '#a8463c'), reward: 180,
      foe: { lv: 6, hpMul: 1.3, el: '木', cats: ['詞義'], moves: [['抄寫連擊', ['詞義'], 45], ['錯字連發', ['字形'], 45]] },
      intro: '抄了一整天的書，手正癢呢！', win: '你的字比我工整……', after: '「抄」不是重點，看懂才是。' },
    t_r2b: { kind: 'trainer', name: '書院生 阿翰', look: stu2('#1a1a20', '#4a6a9a'), reward: 200,
      foe: { lv: 7, hpMul: 1.3, el: '金', cats: ['字音'], moves: [['正音', ['字音'], 48], ['破音字', ['字音'], 48]] },
      intro: '來比比看誰的字音更準！', win: '念對了……我服了。', after: '「模」樣的模念ㄇㄨˊ喔。' },
    t_r3a: { kind: 'trainer', name: '港邊搬運工', look: { hair: '#2a2a2a', cloth: '#4a6a8a' }, reward: 240,
      foe: { lv: 9, hpMul: 1.4, el: '木', cats: ['成語'], moves: [['成語連環', ['成語'], 50], ['典故洪流', ['成語'], 52]] },
      intro: '搬書箱搬到會背成語了，來試試！', win: '哈哈，你贏了！', after: '一箱一箱搬，就像一個一個字慢慢讀。' },
    t_r3b: { kind: 'trainer', name: '書店店員', look: stu2('#5a3a2a', '#3a6a9a', { gender: 'f' }), reward: 260,
      foe: { lv: 10, hpMul: 1.4, el: '水', cats: ['閱讀'], moves: [['速讀', ['閱讀'], 52], ['長文陷阱', ['閱讀'], 54]] },
      intro: '每天整理書，我最會抓重點了！', win: '你的閱讀比我快……', after: '先看題目再看文章，會快很多喔。' },
    t_r5a: { kind: 'trainer', name: '碑林導覽員', look: { hair: '#808080', cloth: '#8a7a5a' }, reward: 320,
      foe: { lv: 14, hpMul: 1.5, el: '土', cats: ['文言', '常識'], moves: [['之乎者也', ['文言'], 55], ['國學常識', ['常識'], 55]] },
      intro: '導覽做久了，古文我可是很熟的。', win: '後生可畏啊。', after: '碑文要先斷句，斷對了意思就出來了。' },
  });

  /* 二週目：硯海龍君（隱藏地圖隨機出現） */
  Object.assign(S.roles, {
    stoneSpirit: { kind: 'spirit', name: '硯海龍君', look: { sprite: 'g_stone' },
      appear: '（島上的墨水一層層退開，硯海龍君睜開了眼睛。）',
      riseLines: ['（三道光沒入池心。水面倒捲成一個漩渦，一座石島從墨海裡升了起來。）',
        '（島上那方巨硯緩緩裂開，一條青色的龍從硯池裡探出頭，鬚上還掛著墨珠。）',
        '……我在這裡等了很久了。',
        '筆會斷、紙會破、墨會乾。只有硯不走——它只是等著，等有人願意磨。',
        '你把三塊碎片帶回來了，說明你走過那三段路。',
        '那就上來吧。讓我看看，你的字裡有沒有真心。'],
      quiz: '硯海龍君低聲問道：「要拿走文房四寶之首，先讓我看看你的底子。」\n（答對才能挑戰牠。）',
      wrong: '硯海龍君搖了搖頭，沉回硯池裡……（再上島一次，牠會再問你一題）',
      intro: '很好。那就讓我看看，你的字裡有沒有真心。',
      win: '……原來如此。筆墨紙都在我的硯海裡成形，而你，讓它們有了意義。',
      after: '（墨池恢復了平靜。）',
      fleeMsg: '硯海龍君化成墨水，從你手邊溜走了……（牠會在墨池的其他地方再出現）',
      reward: 2000, fleeRate: 0.1, potions: 1,
      foe: { lv: 26, hpMul: 2.2, el: 'none', race: null,
        cats: ['文言', '詩詞', '成語', '閱讀', '常識', '修辭', '字形', '字音', '詞義'],
        moves: [['墨海翻湧', ['文言', '詩詞'], 66], ['磨墨千遍', ['成語', '常識'], 66], ['硯波不驚', ['閱讀', '修辭'], 70], ['文心錯亂', ['閱讀'], 76, 'order']] } },
  });
  /* 二週目開場的短劇情（解釋墨塵為什麼回來） */
  S.ngLines = {
    2: ['小墨：「你有沒有發現？這次的墨塵比較安靜，但更黏。」', '「牠們不再亂衝，而是躲在字的後面——像是在等你先鬆懈。」'],
    4: ['小墨：「你已經拿回四片了……」', '「我要老實說：第一次我以為打倒魔王就結束了。現在我才懂，焦慮不會被打倒，只會被理解。」'],
    5: ['小墨：「最後一戰了。這次牠不是在嚇你，是在問你——」', '「『就算沒有人看見，你還願意好好讀嗎？』」'],
  };
  S.ngIntro = [
    '（會考結束了。你以為墨塵散掉了——但今天早自習，黑板上的字又開始滴墨。）',
    '……果然。焦慮不會因為考完一次就消失，它只是換了一個學期、換了一群人。',
    '不過這次不一樣：你已經知道怎麼讀懂它們了，所以牠們也變強了，題目會更難。',
    '還有一件事——墨塵退去之後，校園牆角露出了一道舊墨漬。那底下是傳說中的「硯海墨池」，文房四寶之首「硯海龍君」就沉睡在裡面。',
    '牠不會乖乖等你。要先答對牠的題目才肯出手，打到一半覺得你不夠格，還會直接溜走。',
  ];
  Object.assign(S.roles, {
    tipInk: { name: '掃地的工友伯伯', look: { hair: '#909090', cloth: '#6a8a6a', hat: '#4a6a4a' },
      lines: ['校園中間那道牆角，怎麼掃都掃不乾淨……那不是污漬，是「墨」啦。',
        '聽老一輩說，那底下有個「硯海墨池」。你要是站在牆角前面按確認鍵，說不定進得去喔。'] },
  });
  /* 通關後才會出現的人物 */
  S.postNpcs = {
    aud: [{ role: 'postMo', x: 6, y: 2, dir: 'down' }, { role: 'postBoss', x: 9, y: 2, dir: 'down' }],
    campus: [{ role: 'postRival', x: 12, y: 13, dir: 'down' }, { role: 'tipInk', x: 16, y: 5, dir: 'left' }],
  };
})();
